// Static original images: reuse the actual DOM image between home renders.
const mascotImage121=new Image();mascotImage121.className='mascotPNG121';mascotImage121.width=220;mascotImage121.height=300;mascotImage121.alt='Bulky';mascotImage121.hidden=true;let mascotLevel121=0,mascotRequest121=0;
function mountMascot121(score){const slot=document.getElementById('mascotSlot'),target=R.level(score);if(!slot)return;slot.appendChild(mascotImage121);if(target===mascotLevel121&&mascotImage121.complete&&mascotImage121.naturalWidth){mascotImage121.hidden=false;slot.querySelector('.mascotFallback').hidden=true;return}const request=++mascotRequest121,pending=new Image();pending.onload=()=>{if(request!==mascotRequest121)return;mascotImage121.src=pending.src;mascotImage121.alt='Bulky level '+target+' — '+['Uitgeput','Hongerig','Normaal','Fit','Gespierd'][target-1];mascotImage121.hidden=false;mascotLevel121=target;const current=document.getElementById('mascotSlot');if(current)current.querySelector('.mascotFallback').hidden=true};pending.onerror=()=>{if(request!==mascotRequest121)return;mascotImage121.hidden=true;const current=document.getElementById('mascotSlot');if(current){const label=current.querySelector('.mascotFallback');label.hidden=false;label.textContent='Bulky · level '+target+' · afbeelding niet beschikbaar'}};pending.src='assets/bulky-level-'+target+'.png';
}

function toggleCreatineFor121(date){if(date!==today())return;const d=BulkyCore.ensureDay(db,date),before=d.creatine;d.creatine=!d.creatine;try{save()}catch{d.creatine=before;return}render()}
window.toggleCreatineV11=()=>toggleCreatineFor121(homeDate);
function prNames121(){return [...new Set([...Object.values(db.plans).flatMap(p=>p.map(e=>e[0])),...Object.values(db.workouts).flatMap(w=>(w.exercises||[]).map(e=>e.name))])].sort((a,b)=>a.localeCompare(b,'nl'))}
function renderPRs(){recentPRs.innerHTML=`<div class="between row"><b>Mijn PR’s</b><button class="btn" onclick="pickPR121()">Oefening toevoegen</button></div><p class="sub">Alleen voltooide sessies en afgevinkte sets. Beste set = hoogste geschatte 1RM (Epley).</p>`+(db.prFavorites||[]).map(name=>{const r=R.records(db,name),last=r.rows.at(-1),previous=r.rows.at(-2);return `<div class="item"><div class="between row"><b>${esc(name)}</b><button class="linkbtn" onclick="removePR121(${argument(name)})">Niet meer volgen</button></div>${r.best?`<p>Hoogste gewicht: <b>${nutrientText121(r.weight)} kg</b><br>Beste set: <b>${r.best.kg} × ${r.best.reps}</b><br>Geschatte 1RM: <b>${nutrientText121(r.best.e1)} kg</b></p><div class="sub">Laatste (${esc(last.date)}): ${last.sets.map(s=>s.kg+'×'+s.reps).join(' · ')}${previous?'<br>Daarvoor ('+esc(previous.date)+'): '+previous.sets.map(s=>s.kg+'×'+s.reps).join(' · '):''}</div><button class="linkbtn" onclick="prHistory121(${argument(name)})">Progressie bekijken</button>`:'<p class="muted">Nog geen voltooide sets voor deze oefening.</p>'}</div>`}).join('')+(!db.prFavorites.length?'<p>Kies de oefeningen die je hier wilt volgen.</p>':'')}
function pickPR121(){modal('Oefening volgen','<input id="prQuery121" placeholder="Zoek oefening" oninput="filterPR121()"><div id="prChoices121"></div>');filterPR121()}
function filterPR121(){const q=R.norm(prQuery121.value);prChoices121.innerHTML=prNames121().filter(n=>R.norm(n).includes(q)&&!db.prFavorites.includes(n)).map(n=>`<button class="btn sec full" onclick="addPR121(${argument(n)})">${esc(n)}</button>`).join('')||'<p>Geen andere oefeningen gevonden.</p>'}
function addPR121(name){if(!db.prFavorites.includes(name))db.prFavorites.push(name);save();closeModal();renderPRs()}
function removePR121(name){db.prFavorites=db.prFavorites.filter(n=>n!==name);save();renderPRs()}
function prHistory121(name){const r=R.records(db,name);modal(name,r.rows.slice().reverse().map(row=>`<div class="item"><b>${esc(fullDate(row.date))}</b><p>${row.sets.map(s=>s.kg+'×'+s.reps).join(' · ')}</p><div class="sub">Beste e1RM ${nutrientText121(Math.max(...row.sets.map(s=>s.e1)))} kg</div></div>`).join(''))}
function timerPaint121(){const t=db.restTimer;document.body.classList.toggle('hasRest121',!!t);if(!t){restTimer.style.display='none';return}const ms=R.remaining(t),seconds=Math.ceil(ms/1000);if(t.status==='running'&&ms===0){t.status='finished';save()}if(t.status==='finished'&&!t.announced&&!document.hidden){t.announced=true;save();toast('Rust voorbij — klaar voor je volgende set.');try{navigator.vibrate?.([180,80,180])}catch{}}
 restTimer.style.display='block';restTimer.innerHTML=`<div role="timer" aria-label="Rusttimer"><b>${t.status==='finished'?'Rust voorbij':t.status==='paused'?'Rust gepauzeerd':'Rust'}</b><div class="big">${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}</div></div><div class="row">${t.status==='running'?'<button class="linkbtn" onclick="pauseRest121()">Pauze</button>':t.status==='paused'?'<button class="linkbtn" onclick="resumeRest121()">Hervatten</button>':''}<button class="linkbtn" onclick="stopRestTimer()">${t.status==='finished'?'Sluiten':'Stoppen'}</button></div>`}
window.startRestTimer=seconds=>{let duration;try{duration=Math.min(3600,R.positive(seconds))*1000}catch{alert('Controleer de rusttijd in Instellingen.');return}db.restTimer={status:'running',endAt:Date.now()+duration,remainingMs:duration,announced:false};save();timerPaint121()};
function pauseRest121(){const t=db.restTimer;if(t?.status!=='running')return;t.remainingMs=R.remaining(t);t.status='paused';save();timerPaint121()}
function resumeRest121(){const t=db.restTimer;if(t?.status!=='paused')return;t.endAt=Date.now()+t.remainingMs;t.status='running';save();timerPaint121()}
window.stopRestTimer=()=>{db.restTimer=null;save();timerPaint121()};
setInterval(timerPaint121,500);document.addEventListener('visibilitychange',()=>{if(!document.hidden)timerPaint121()});window.addEventListener('pageshow',timerPaint121);
const existingFinishOnboard121=window.finishOnboarding;window.finishOnboarding=()=>{if(db.profile.onboardingCompleted){document.getElementById('onboarding').classList.remove('on');return}if(!onName.value.trim()||!(+onKcal.value>0)||!(+onProtein.value>0))return alert('Vul een naam en geldige doelen in.');const previousProfile=clone(db.profile);existingFinishOnboard121();db.profile={...previousProfile,...db.profile,onboardingCompleted:true};save()};
function showOnboarding(){if(db.profile.onboardingCompleted)return;onName.value=db.profile.name||'';onKcal.value=db.settings.kcal||3150;onProtein.value=db.settings.protein||160;onCreatine.value=db.profile.creatineGoal||5;document.getElementById('onboarding').classList.add('on')}
// Storage availability and migration failures never fall back to fresh() silently.
render();timerPaint121();if(!db.profile.onboardingCompleted)setTimeout(()=>{if(!db.profile.onboardingCompleted)showOnboarding()},120);
if('serviceWorker' in navigator){navigator.serviceWorker.register('./sw.js',{updateViaCache:'none'}).catch(e=>console.warn('Offline installatie mislukt',e));/* No forced mid-workout reload. Each worker serves its own complete shell. */}

window.saveWorkoutSettings=()=>{const sec=Number(restSeconds.value);if(!Number.isInteger(sec)||sec<5||sec>3600)return alert('Kies 5 tot en met 3600 seconden.');db.workoutSettings={...db.workoutSettings,restSeconds:sec};save();toast('Rusttijd opgeslagen.')}
