
const KEY='leanbulk_v1',V=19,clone=x=>JSON.parse(JSON.stringify(x)),today=()=>localDateKey(new Date()),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
// Civil dates are local calendar dates, never UTC timestamps or locale-dependent keys.
function localDateKey(d){return BulkyCore.dateKey(d)}
function validDateKey(s){return BulkyCore.validDate(s)}
function normalizeWorkoutData(data){return BulkyCore.migrate(data)}
function isCompleted(w){return w.finished===true}
function hasWorkoutInput(w){return (w.exercises||[]).some(e=>(e.sets||[]).some(s=>s.done||+s.kg||+s.reps))}
function plannedWorkouts(date){let name=BulkyCore.schedule(db,date).name;return name?[name]:[]}
const basePlans={Push:[['Bench press',3,'6-8'],['Incline dumbbell press',3,'8-10'],['Cable/machine chest fly',2,'10-15'],['Shoulder press',3,'8-10'],['Lateral raise',3,'12-20'],['Tricep pushdown',3,'10-15'],['Overhead tricep extension',2,'10-15']],Pull:[['Pull-ups / lat pulldown',3,'6-10'],['Chest-supported row',3,'8-12'],['Seated cable row',3,'8-12'],['Rear delt fly',3,'12-20'],['EZ-bar curl',3,'8-12'],['Hammer curl',2,'10-15']],Benen:[['Squat / hack squat',3,'6-10'],['Romanian deadlift',3,'6-10'],['Leg press',3,'10-15'],['Leg curl',3,'10-15'],['Leg extension',3,'10-15'],['Calf raises',4,'10-15']],Upper:[['Incline bench press',3,'6-10'],['Machine chest press',2,'8-12'],['Lat pulldown',3,'8-12'],['Chest-supported row',3,'8-12'],['Cable fly',2,'12-15'],['Cable row',2,'10-15'],['Bicep curl',2,'10-15'],['Tricep pushdown',2,'10-15']],['Schouders & Armen']:[['Shoulder press',3,'6-10'],['Cable lateral raise',4,'12-20'],['Rear delt fly',3,'12-20'],['EZ-bar/preacher curl',3,'8-12'],['Incline dumbbell curl',3,'10-15'],['Hammer curl',2,'10-15'],['Tricep pushdown',3,'10-15'],['Overhead tricep extension',3,'10-15']]};
function fresh(){return{version:V,settings:{kcal:3150,protein:160},days:{},workouts:{},plans:clone(basePlans),products:{},meals:{},recent:[]}}
const originalStorage=localStorage.getItem(KEY);let hadExistingData=!!originalStorage;let db;
try{if(originalStorage&&!localStorage.getItem(KEY+'_pre_v12_1'))localStorage.setItem(KEY+'_pre_v12_1',originalStorage);db=originalStorage?normalizeWorkoutData(JSON.parse(originalStorage)):fresh();if(originalStorage&&db.version!==V)localStorage.setItem(KEY+'_pre_v17',originalStorage)}catch(error){alert('Je opgeslagen gegevens zijn niet gewijzigd. Migratie gestopt: '+error.message);throw error}
function migrate(){db=normalizeWorkoutData(db);db.settings=db.settings||{kcal:3150,protein:160};db.profile=db.profile||{name:'',creatineGoal:5,onboarded:false};db.calculator=db.calculator||{};db.workoutSettings=db.workoutSettings||{restSeconds:120};db.days=db.days||{};
db.game=db.game||{xp:0,xpDays:{},claimedAchievements:{},questClaims:{},friends:[],feed:[]};
db.game.xp=+db.game.xp||0;db.game.xpDays=db.game.xpDays||{};db.game.claimedAchievements=db.game.claimedAchievements||{};db.game.questClaims=db.game.questClaims||{};db.game.friends=db.game.friends||[];db.game.feed=db.game.feed||[];db.workouts=db.workouts||{};db.plans=db.plans||clone(basePlans);db.products=db.products||{};db.meals=db.meals||{};db.recent=db.recent||[];db.searchCache=db.searchCache||{};Object.values(db.days).forEach(d=>{d.foods=d.foods||[];/* Preserve null = unknown nutrients. */});db.version=V;save()}function save(){try{localStorage.setItem(KEY,JSON.stringify(db))}catch(e){alert('Opslaan is mislukt. Maak een back-up en controleer de vrije opslagruimte. Sluit de app nog niet.');throw e}}migrate();
const D=['Zondag','Maandag','Dinsdag','Woensdag','Donderdag','Vrijdag','Zaterdag'],schedule={1:'Push',2:'Pull',3:'⚽ Voetbal 75 min',4:'Benen',5:'Upper',6:'⚽ Wedstrijd 90 min',0:'Schouders & Armen'};let selected=(schedule[new Date().getDay()]||'Push').replace('⚽ Voetbal 75 min','Push').replace('⚽ Wedstrijd 90 min','Upper');if(!db.plans[selected])selected=Object.keys(db.plans)[0];
function day(){return BulkyCore.ensureDay(db,today())}function totals(){return day().foods.reduce((a,f)=>({k:a.k+(+f.kcal||0),p:a.p+(+f.protein||0),c:a.c+(+f.carbs||0),f:a.f+(+f.fat||0)}),{k:0,p:0,c:0,f:0})}

function applyBulkyTheme(){const dark=localStorage.getItem('bulky_theme')==='dark';document.body.classList.toggle('bulkyDark',dark);const b=document.getElementById('bulkyThemeToggle');if(b)b.textContent=dark?'☀':'☾'}
window.toggleBulkyTheme=()=>{localStorage.setItem('bulky_theme',document.body.classList.contains('bulkyDark')?'light':'dark');applyBulkyTheme()}
setTimeout(applyBulkyTheme,0);
function totalsV11(){return(day().foods||[]).reduce((a,f)=>({k:a.k+(+f.kcal||0),p:a.p+(+f.protein||0),c:a.c+(+f.carbs||0),f:a.f+(+f.fat||0)}),{k:0,p:0,c:0,f:0})}
function renderV11(){renderHome()}
window.toggleCreatineV11=()=>{day().creatine=!day().creatine;render()}
window.quickWeightV11=()=>modal('Gewicht loggen',`<div class="field"><label>Gewicht vandaag (kg)</label><input id="qw11" type="number" inputmode="decimal" step=".1" value="${day().weight||''}"></div><button class="btn" style="width:100%" onclick="saveQuickWeightV11()">Opslaan</button>`)
window.saveQuickWeightV11=()=>{day().weight=+qw11.value||null;closeModal();render()}
window.openWorkoutV11=n=>{selected=n;document.querySelector('[data-p=workout]').click();renderWorkout()}
window.openQuickV11=()=>modal('Snel toevoegen',`<div class="quickGrid" style="margin-top:12px"><button class="quickTile" onclick="closeModal();openAddMenu()">🍎<strong>Voeding</strong><small>Product of maaltijd</small></button><button class="quickTile" onclick="closeModal();startScan()">📷<strong>Barcode</strong><small>Scan product</small></button><button class="quickTile" onclick="closeModal();quickWeightV11()"><span style="font-size:18px">◫</span><strong>Gewicht</strong><small>Log gewicht</small></button><button class="quickTile" onclick="closeModal();document.querySelector('[data-p=progress]').click();setTimeout(()=>photoInput.click(),100)">📸<strong>Progressiefoto</strong><small>Nieuwe foto</small></button></div>`)
window.toggleDarkV11=()=>{let on=!document.body.classList.contains('v11dark');document.body.classList.toggle('v11dark',on);localStorage.setItem('leanbulk_dark',on?'1':'0')}
if(localStorage.getItem('leanbulk_dark')==='1')document.body.classList.add('v11dark');

function render(){let t=totals();date.textContent=new Date().toLocaleDateString('nl-NL',{weekday:'long',day:'numeric',month:'long'});daypill.textContent=schedule[new Date().getDay()];kc.textContent=Math.round(t.k);kg.textContent=db.settings.kcal;pr.textContent=Math.round(t.p)+'g';ca.textContent=Math.round(t.c)+'g';fa.textContent=Math.round(t.f)+'g';cr.textContent=day().creatine?'✓ '+(db.profile?.creatineGoal||5)+'g':'—';left.textContent=Math.max(0,db.settings.kcal-t.k).toFixed(0)+' kcal over';kbar.style.width=Math.min(100,t.k/db.settings.kcal*100)+'%';foods.innerHTML=day().foods.length?day().foods.map((f,i)=>`<div class="item between row"><div><b>${esc(f.name)}</b><div class="small muted">${Math.round(f.kcal)} kcal · ${(+f.protein).toFixed(1)}g eiwit${f.qtyLabel?' · '+esc(f.qtyLabel):''}</div></div><button class="linkbtn" onclick="delFood(${i})">Verwijder</button></div>`).join(''):'<div class="muted item">Nog niets gelogd.</div>';let ws=Object.entries(db.days).filter(([k,d])=>d.weight).sort().slice(-7).map(x=>+x[1].weight);avg.textContent=ws.length?(ws.reduce((a,b)=>a+b,0)/ws.length).toFixed(1)+' kg':'—';weight.value=day().weight||'';goalK.value=db.settings.kcal;goalP.value=db.settings.protein;if(window.profileName)profileName.value=db.profile?.name||'';if(window.goalC)goalC.value=db.profile?.creatineGoal||5;if(window.restSeconds)restSeconds.value=db.workoutSettings?.restSeconds||120;renderLibrary();renderWorkout();renderProgress();renderCalcSummary();renderCoach();renderGame();renderFriends();renderV11();save()}
creatine.onclick=()=>{day().creatine=!day().creatine;render()};window.delFood=i=>{day().foods.splice(i,1);render()};window.saveWeight=()=>{day().weight=+weight.value||null;render()};window.saveGoals=()=>{db.settings.kcal=+goalK.value||3150;db.settings.protein=+goalP.value||160;render()};window.saveProfile=()=>{db.profile=db.profile||{};db.profile.name=profileName.value.trim();db.profile.creatineGoal=+goalC.value||5;db.profile.onboarded=true;save();render();alert('Profiel opgeslagen.');};window.saveWorkoutSettings=()=>{db.workoutSettings={restSeconds:+restSeconds.value||120};save();alert('Workout instellingen opgeslagen.');};
document.querySelectorAll('.nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav button').forEach(x=>x.classList.remove('on'));b.classList.add('on');document.querySelectorAll('.page').forEach(x=>x.classList.remove('on'));document.getElementById(b.dataset.p).classList.add('on');if(b.dataset.p==='today'){renderHome();}if(b.dataset.p==='workout')renderWorkout();if(b.dataset.p==='progress')setTimeout(drawCharts,20)});
function modal(title,html){mtitle.textContent=title;mbody.innerHTML=html;document.getElementById('modal').classList.add('on')}window.closeModal=()=>document.getElementById('modal').classList.remove('on');
window.openAddMenu=()=>modal('Toevoegen',`<div class="grid2" style="margin-top:12px"><button class="btn" onclick="openCatalogSearch()">🔎 Product zoeken</button><button class="btn sec" onclick="startScan()">📷 Barcode scannen</button><button class="btn sec" onclick="manualBarcode()">Barcode invoeren</button><button class="btn sec" onclick="pickProduct()">Product kiezen</button><button class="btn sec" onclick="pickMeal()">Maaltijd kiezen</button></div>`);window.openProducts=()=>{document.querySelector('[data-p=library]').click()};
function productForm(p={},code=''){return `<div class="field"><label>Naam</label><input id="pn" value="${esc(p.name||'')}"></div><div class="field"><label>Barcode (optioneel)</label><input id="pb" inputmode="numeric" value="${esc(code||p.barcode||'')}"></div><div class="grid2"><div class="field"><label>Waarden zijn per</label><select id="ptype"><option value="100g" ${p.type==='100g'?'selected':''}>100 gram</option><option value="100ml" ${p.type==='100ml'?'selected':''}>100 ml</option><option value="unit" ${p.type==='unit'?'selected':''}>1 stuk / portie</option></select></div><div class="field"><label>Naam eenheid</label><input id="punit" value="${esc(p.unit||'stuk')}" placeholder="snee, banaan, portie"></div></div><div class="grid2"><div class="field"><label>kcal</label><input id="pk" type="text" inputmode="decimal" value="${p.kcal??''}"></div><div class="field"><label>Eiwit g</label><input id="pp" type="text" inputmode="decimal" value="${p.protein??''}"></div><div class="field"><label>Koolhydraten g</label><input id="pc" type="text" inputmode="decimal" value="${p.carbs??''}"></div><div class="field"><label>Vet g</label><input id="pf" type="text" inputmode="decimal" value="${p.fat??''}"></div></div><div class="grid2"><div class="field"><label>Snelle portie (optioneel)</label><input id="pserv" type="text" inputmode="decimal" value="${p.serving??''}" placeholder="bijv. 38"></div><div class="field"><label>Portienaam</label><input id="pservname" value="${esc(p.servingName||'')}" placeholder="bijv. 1 snee"></div></div><div class="small muted" style="margin:-4px 0 10px">Voorbeeld: brood per 100 g, snelle portie 38 g = “1 snee”. Pindakaas: 15 g = “1 beleg”.</div><button class="btn" style="width:100%" onclick="saveProduct('${esc(p.id||'')}')">Product opslaan</button>`}
window.openProductEditor=(id='')=>{let p=id?db.products[id]:{};modal(id?'Product aanpassen':'Nieuw product',productForm(p,p.barcode))};window.deleteProduct=id=>{if(confirm('Product verwijderen? Bestaande logs blijven staan.')){delete db.products[id];render()}};
window.pickProduct=()=>{let ps=Object.values(db.products);modal('Product loggen',ps.length?ps.map(p=>`<button class="btn sec" style="width:100%;margin-top:7px" onclick="logProduct('${p.id}')">${esc(p.name)}</button>`).join(''):'<div class="muted">Maak of scan eerst een product.</div>')};window.pickMeal=()=>{let ms=Object.values(db.meals);modal('Maaltijd loggen',ms.length?ms.map(m=>`<button class="btn sec" style="width:100%;margin-top:7px" onclick="logMeal('${m.id}')">${esc(m.name)}</button>`).join(''):'<div class="muted">Maak eerst een maaltijd.</div>')};
function showOnboarding(){document.getElementById('onboarding').classList.add('on')}
window.finishOnboarding=()=>{db.profile={name:onName.value.trim(),creatineGoal:+onCreatine.value||5,onboarded:true};db.settings.kcal=+onKcal.value||3150;db.settings.protein=+onProtein.value||160;if(onPlan.value==='empty'){db.plans={'Mijn workout':[]};selected='Mijn workout'}let sw=+onWeight.value||0;if(sw)day().weight=sw;save();document.getElementById('onboarding').classList.remove('on');render();if(onPlan.value==='empty')setTimeout(()=>editPlans(),80)};
window.exportPlan=()=>{let payload={type:'leanbulk-workout-plan',version:1,exported:new Date().toISOString(),plans:db.plans};let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}));a.download='leanbulk-workout-schema.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
window.importPlanFile=async f=>{try{let j=JSON.parse(await f.text());if(j.type!=='leanbulk-workout-plan'||!j.plans||typeof j.plans!=='object')throw 0;if(!confirm('Dit vervangt alleen je huidige workout-schema. Je workoutgeschiedenis en progressie blijven staan. Doorgaan?'))return;db.plans=j.plans;if(!Object.keys(db.plans).length)db.plans={'Mijn workout':[]};selected=Object.keys(db.plans)[0];save();render();alert('Schema geïmporteerd.')}catch{alert('Dit is geen geldig Lean Bulk workout-schema.')}};
setTimeout(()=>{if(window.planInput)planInput.onchange=()=>{let f=planInput.files?.[0];if(f)importPlanFile(f);planInput.value=''}},0);


function calcDefaults(){let c=db.calculator||{},latest=Object.entries(db.days).filter(x=>x[1].weight).sort().at(-1)?.[1]?.weight||'';return{sex:c.sex||'man',age:c.age||22,height:c.height||183,weight:c.weight||latest||76,activity:c.activity||'1.55',goal:c.goal||'lean',pace:c.pace||'normal'}}
window.openCalorieCalculator=()=>{let c=calcDefaults();modal('Caloriebehoefte berekenen',`<div class="notice">Dit is een startschatting. Je echte behoefte wordt duidelijker uit je gemiddelde calorie-inname en gewichtstrend over meerdere weken.</div><div class="grid2"><div class="field"><label>Geslacht voor BMR-formule</label><select id="csex"><option value="man" ${c.sex==='man'?'selected':''}>Man</option><option value="vrouw" ${c.sex==='vrouw'?'selected':''}>Vrouw</option></select></div><div class="field"><label>Leeftijd</label><input id="cage" type="number" value="${c.age}"></div></div><div class="grid2"><div class="field"><label>Lengte (cm)</label><input id="cheight" type="number" value="${c.height}"></div><div class="field"><label>Gewicht (kg)</label><input id="cweight" type="number" step=".1" value="${c.weight}"></div></div><div class="field"><label>Dagelijkse activiteit</label><select id="cactivity"><option value="1.2" ${c.activity==='1.2'?'selected':''}>Weinig beweging / zittend</option><option value="1.375" ${c.activity==='1.375'?'selected':''}>Licht actief</option><option value="1.55" ${c.activity==='1.55'?'selected':''}>Gemiddeld actief</option><option value="1.725" ${c.activity==='1.725'?'selected':''}>Zeer actief / veel sport</option><option value="1.9" ${c.activity==='1.9'?'selected':''}>Extreem actief / fysiek werk + sport</option></select></div><div class="field"><label>Doel</label><select id="cgoal" onchange="document.getElementById('paceWrap').style.display=this.value==='lean'?'block':'none'"><option value="cut" ${c.goal==='cut'?'selected':''}>Afvallen</option><option value="maintain" ${c.goal==='maintain'?'selected':''}>Gewicht onderhouden</option><option value="lean" ${c.goal==='lean'?'selected':''}>Lean bulk / rustig spiermassa opbouwen</option><option value="gain" ${c.goal==='gain'?'selected':''}>Sneller aankomen</option></select></div><div id="paceWrap" class="field" style="display:${c.goal==='lean'?'block':'none'}"><label>Lean-bulk tempo</label><select id="cpace"><option value="slow" ${c.pace==='slow'?'selected':''}>Langzaam — minimale vettoename</option><option value="normal" ${c.pace==='normal'?'selected':''}>Normaal</option><option value="fast" ${c.pace==='fast'?'selected':''}>Sneller</option></select></div><button class="btn" style="width:100%" onclick="calculateCalories()">Bereken mijn behoefte</button><div id="calcResult"></div>`)}
window.calculateCalories=()=>{let sex=csex.value,age=+cage.value,h=+cheight.value,w=+cweight.value,af=+cactivity.value,goal=cgoal.value,pace=document.getElementById('cpace')?.value||'normal';if(!age||!h||!w)return alert('Vul leeftijd, lengte en gewicht in.');let bmr=10*w+6.25*h-5*age+(sex==='man'?5:-161),maint=Math.round(bmr*af),delta=goal==='cut'?-400:goal==='maintain'?0:goal==='gain'?400:pace==='slow'?150:pace==='fast'?300:225,target=Math.round((maint+delta)/10)*10,protein=Math.round(w*2);db.calculator={sex,age,height:h,weight:w,activity:String(af),goal,pace,lastBmr:Math.round(bmr),lastMaintenance:maint,lastTarget:target,lastProtein:protein,calculatedAt:Date.now()};save();calcResult.innerHTML=`<div class="card" style="background:var(--soft)"><div class="grid2"><div class="stat"><span class="small muted">Rustverbranding</span><b>${Math.round(bmr)} kcal</b></div><div class="stat"><span class="small muted">Onderhoud schatting</span><b>${maint} kcal</b></div></div><div style="text-align:center;margin:13px 0"><div class="small muted">Voorgesteld dagelijks doel</div><div class="big">${target} kcal</div><div class="small muted">Eiwitvoorstel: ±${protein} g/dag</div></div><button class="btn good" style="width:100%" onclick="applyCalculatedGoal()">Gebruik dit als mijn doel</button></div>`}
window.applyCalculatedGoal=()=>{let c=db.calculator;if(!c?.lastTarget)return;db.settings.kcal=c.lastTarget;db.settings.protein=c.lastProtein||db.settings.protein;day().goals=clone(db.settings);save();closeModal();render();alert('Nieuw calorie- en eiwitdoel ingesteld.');}
function renderCalcSummary(){let el=document.getElementById('calcSummary'),c=db.calculator;if(!el)return;el.textContent=c?.lastTarget?`Laatste berekening: ${c.lastTarget} kcal/dag · onderhoud ±${c.lastMaintenance} kcal`:'Nog geen berekening gemaakt.'}


window.progressTab=(name,btn)=>{document.querySelectorAll('.progpanel').forEach(x=>x.classList.add('hide'));document.getElementById('prog-'+name)?.classList.remove('hide');document.querySelectorAll('#progressTabs .tab').forEach(x=>x.classList.remove('on'));btn?.classList.add('on');if(name==='muscles')renderMuscleVolume();if(name==='journey')renderJourney();if(name==='prs')renderPRs();if(name==='photos')loadPhotos().catch(()=>alert('Foto-opslag is niet beschikbaar.'));if(name==='strength')drawCharts()};

const XP_PER_LEVEL=1000;
function levelInfo(){let xp=+db.game.xp||0,lvl=Math.floor(xp/XP_PER_LEVEL)+1,inside=xp%XP_PER_LEVEL;return{xp,lvl,inside,pct:inside/XP_PER_LEVEL*100,next:XP_PER_LEVEL-inside,title:lvl>=50?'Legend':lvl>=25?'Veteran':lvl>=10?'Iron':lvl>=5?'Regular':'Rookie'}}
function toast(s){let x=document.createElement('div');x.className='toast';x.setAttribute('role','status');x.textContent=s;document.body.appendChild(x);setTimeout(()=>x.remove(),2600)}
function awardXP(n,reason,key){if(key&&db.game.questClaims[key])return false;if(key)db.game.questClaims[key]=Date.now();db.game.xp=(+db.game.xp||0)+n;db.game.feed.unshift({t:Date.now(),text:`+${n} XP · ${reason}`});db.game.feed=db.game.feed.slice(0,40);save();toast(`⭐ +${n} XP — ${reason}`);return true}
function validWorkoutForXP(w){let sets=(w.exercises||[]).flatMap(e=>(e.sets||[])).filter(s=>s.done&&+s.reps>0);return w.finished&&sets.length>=4}
function claimWorkoutXP(w){let d=w.date||today();if(db.game.xpDays[d])return false;if(!validWorkoutForXP(w))return false;db.game.xpDays[d]={at:Date.now(),workout:w.name};awardXP(100,'Workout voltooid','workout:'+d);return true}
function finishedWorkoutDays(){return [...new Set(Object.values(db.workouts).filter(validWorkoutForXP).map(w=>w.date))].sort()}
function weekKey(d=new Date()){let x=new Date(d);x.setHours(0,0,0,0);let day=(x.getDay()+6)%7;x.setDate(x.getDate()-day);return localDateKey(x)}
function weekWorkoutCount(offset=0){let start=new Date();start.setHours(0,0,0,0);start.setDate(start.getDate()-((start.getDay()+6)%7)-offset*7);let end=new Date(start);end.setDate(end.getDate()+7);return Object.values(db.workouts).filter(validWorkoutForXP).filter(w=>{let d=new Date(w.date+'T12:00:00');return d>=start&&d<end}).length}
function weekStreak(){let n=0;for(let i=0;i<100;i++){if(weekWorkoutCount(i)>=3)n++;else if(i===0)continue;else break}return n}
function foodGoalDays(){return Object.entries(db.days).filter(([k,d])=>{let t=(d.foods||[]).reduce((a,f)=>a+(+f.protein||0),0);return t>=(d.goals?.protein||db.settings.protein||160)*.9}).map(x=>x[0])}
function achievementDefs(){let ls=lifetimeStats(),sessions=Object.values(db.workouts).filter(validWorkoutForXP).length,st=weekStreak();return[
{id:'first',icon:'🥉',name:'First Rep',desc:'Voltooi je eerste echte workout.',rarity:'Common',v:sessions,g:1},
{id:'ten',icon:'🏋️',name:'Getting Started',desc:'10 workouts voltooid.',rarity:'Common',v:sessions,g:10},
{id:'fifty',icon:'⚡',name:'Gym Regular',desc:'50 workouts voltooid.',rarity:'Rare',v:sessions,g:50},
{id:'hundred',icon:'💯',name:'Century Club',desc:'100 workouts voltooid.',rarity:'Epic',v:sessions,g:100},
{id:'streak4',icon:'🔥',name:'Locked In',desc:'4 weken achter elkaar minimaal 3 workouts.',rarity:'Rare',v:st,g:4},
{id:'100t',icon:'🏋️',name:'Plate Collector',desc:'100.000 kg lifetime trainingsvolume.',rarity:'Rare',v:ls.total,g:100000},
{id:'500t',icon:'🚜',name:'Heavy Machinery',desc:'500.000 kg lifetime trainingsvolume.',rarity:'Epic',v:ls.total,g:500000},
{id:'alien',icon:'👽',name:'Certified Alien',desc:'1.000.000 kg lifetime trainingsvolume.',rarity:'Legendary',v:ls.total,g:1000000},
{id:'protein30',icon:'🥩',name:'Protein Machine',desc:'30 dagen minimaal 90% van je eiwitdoel gelogd.',rarity:'Epic',v:foodGoalDays().length,g:30}
]}
function achievementProgress(a){return{done:a.v>=a.g,pct:Math.min(100,a.v/a.g*100)}}
function checkAchievements(){for(let a of achievementDefs()){if(achievementProgress(a).done&&!db.game.claimedAchievements[a.id]){db.game.claimedAchievements[a.id]=Date.now();db.game.xp+=50;db.game.feed.unshift({t:Date.now(),text:`🏅 ${a.name} ontgrendeld · +50 XP`});toast(`🏅 ${a.name} — +50 XP`);save()}}}
function quests(){let wk=weekKey(),wc=weekWorkoutCount(0),protein=foodGoalDays().filter(d=>d>=wk).length,weights=Object.entries(db.days).filter(([d,x])=>d>=wk&&x.weight).length;return[
{id:'w3:'+wk,name:'3 workouts deze week',v:wc,g:3,xp:75,icon:'🏋️'},
{id:'p3:'+wk,name:'3 dagen eiwitdoel',v:protein,g:3,xp:50,icon:'🥩'},
{id:'kg3:'+wk,name:'3× lichaamsgewicht loggen',v:weights,g:3,xp:35,icon:'⚖️'}]}
function autoClaimQuests(){for(let q of quests())if(q.v>=q.g&&!db.game.questClaims[q.id])awardXP(q.xp,q.name,q.id)}
function renderGame(){checkAchievements();autoClaimQuests();let L=levelInfo();if(document.getElementById('todayLevel'))todayLevel.textContent='Level '+L.lvl;if(document.getElementById('todayTitle'))todayTitle.textContent='· '+L.title;if(document.getElementById('todayXpBar'))todayXpBar.style.width=L.pct+'%';if(document.getElementById('todayXpText'))todayXpText.textContent=L.inside+' / 1.000 XP';if(document.getElementById('todayStreak'))todayStreak.textContent='🔥 '+weekStreak()+' week streak';renderJourney()}
let journeyDemo=false;
function renderJourney(){
 let el=document.getElementById('journeyPanel');if(!el)return;
 let L=levelInfo(),qs=quests(),achs=achievementDefs(),st=weekStreak(),wc=weekWorkoutCount(0);
 if(journeyDemo){
   L={xp:7420,lvl:8,inside:420,pct:42,next:580,title:'Regular'};st=6;wc=4;
   qs=[{id:'demo1',name:'3 workouts deze week',v:3,g:3,xp:75,icon:'🏋️'},{id:'demo2',name:'3 dagen eiwitdoel',v:2,g:3,xp:50,icon:'🥩'},{id:'demo3',name:'3× lichaamsgewicht loggen',v:1,g:3,xp:35,icon:'⚖️'}];
   achs=achs.map((a,i)=>({...a,v:i<4?a.g:Math.min(a.v||0,a.g*.62)}));
 }
 let un=achs.filter(a=>achievementProgress(a).done).length;
 el.innerHTML=`<div class="journeyHero">
   <div class="between row"><div><div class="sub">${journeyDemo?'TESTWEERGAVE':'JOUW JOURNEY'}</div><div style="font-size:27px;font-weight:900">Level ${L.lvl}</div><div class="small" style="opacity:.85">${L.title}</div></div><div style="font-size:42px">⭐</div></div>
   <div class="xpbar"><i style="width:${L.pct}%"></i></div>
   <div class="between row small"><span>${L.inside.toLocaleString('nl-NL')} / 1.000 XP</span><b>${L.next} XP → level ${L.lvl+1}</b></div>
 </div>
 <div class="grid2 journeyStats">
   <div class="journeyStat"><span class="jsIcon">⭐</span><span class="small muted"> Totaal XP</span><b>${L.xp.toLocaleString('nl-NL')}</b></div>
   <div class="journeyStat"><span class="jsIcon">🔥</span><span class="small muted"> Week streak</span><b>${st} weken</b></div>
   <div class="journeyStat"><span class="jsIcon">🏅</span><span class="small muted"> Achievements</span><b>${un}/${achs.length}</b></div>
   <div class="journeyStat"><span class="jsIcon">🏋️</span><span class="small muted"> Deze week</span><b>${wc} workouts</b></div>
 </div>
 <div class="card"><div class="sectionTitle"><div><b>🎯 Weekly quests</b><div class="sub">Kleine doelen voor extra XP.</div></div></div>
   ${qs.map(q=>{let done=q.v>=q.g,claimed=journeyDemo?done:!!db.game.questClaims[q.id];return`<div class="questCard ${done?'done':''}"><div class="between row"><span><b>${q.icon} ${esc(q.name)}</b></span><b>${Math.min(q.v,q.g)}/${q.g}</b></div><div class="bar"><div class="fill" style="width:${Math.min(100,q.v/q.g*100)}%"></div></div><div class="small muted" style="margin-top:5px">${claimed?'✓ Voltooid · +'+q.xp+' XP':'Beloning: +'+q.xp+' XP'}</div></div>`}).join('')}
 </div>
 <div class="card"><div class="sectionTitle"><div><b>🏅 Medaillekast</b><div class="sub">Behaald én nog te behalen.</div></div><span class="pill">${un}/${achs.length}</span></div>
   <div class="medalGrid">${achs.map(a=>{let p=achievementProgress(a);let val=Math.min(a.v,a.g);return`<div class="medalTile ${p.done?'':'lockedAch'}"><span class="rarity ${esc(a.rarity)}">${esc(a.rarity)}</span><div class="achIcon">${p.done?a.icon:'🔒'}</div><b>${esc(a.name)}</b><div class="small muted" style="margin-top:3px">${esc(a.desc)}</div>${p.done?`<div class="small" style="margin-top:8px">✓ Behaald</div>`:`<div class="bar"><div class="fill" style="width:${p.pct}%"></div></div><div class="small muted" style="margin-top:4px">${Math.round(val).toLocaleString('nl-NL')} / ${Math.round(a.g).toLocaleString('nl-NL')}</div>`}</div>`}).join('')}</div>
 </div>
 <div class="card testCard"><div class="sectionTitle"><div><b>🧪 Test Journey</b><div class="sub">Test de interface zonder je echte data aan te passen.</div></div></div>
   <div class="grid2"><button class="btn sec" onclick="toggleJourneyDemo()">${journeyDemo?'Echte data tonen':'Demo-data tonen'}</button><button class="btn sec" onclick="runJourneyTests()">Zelftest uitvoeren</button></div><div id="journeyTestResults"></div>
 </div>`;
}
window.toggleJourneyDemo=()=>{journeyDemo=!journeyDemo;renderJourney()}
window.runJourneyTests=()=>{
 let tests=[
 ['Journey-paneel bestaat',!!document.getElementById('prog-journey')],
 ['Medaillekast zichtbaar',!!document.querySelector('.medalGrid')],
 ['XP-opslag aanwezig',!!db.game&&typeof db.game.xp==='number'],
 ['Daglimiet XP aanwezig',!!db.game&&!!db.game.xpDays],
 ['Workoutdata intact',!!db.workouts],
 ['Voedingsdata intact',!!db.days],
 ['Foto-opslag beschikbaar','indexedDB' in window]
 ];
 let box=document.getElementById('journeyTestResults');if(box)box.innerHTML='<div style="margin-top:9px">'+tests.map(t=>`<div class="testResult">${t[1]?'✅':'❌'} ${t[0]}</div>`).join('')+'</div>';
 toast(tests.every(t=>t[1])?'✅ Journey zelftest geslaagd':'⚠️ Zelftest vond een probleem');
}
function profilePayload(){let L=levelInfo(),last=Object.values(db.workouts).filter(validWorkoutForXP).sort((a,b)=>(b.finishedAt||0)-(a.finishedAt||0))[0];return{v:1,name:db.profile?.name||'Gym friend',level:L.lvl,title:L.title,xp:L.xp,streak:weekStreak(),badges:achievementDefs().filter(a=>achievementProgress(a).done).slice(-3).map(a=>a.icon+' '+a.name),last:last?{name:last.name,date:last.date,volume:BulkyCore.volume(last)}:null}}
window.shareProfile=async()=>{let p=profilePayload(),code=btoa(unescape(encodeURIComponent(JSON.stringify(p))));let txt=`${p.name} · Level ${p.level} ${p.title}\n⭐ ${p.xp} XP · 🔥 ${p.streak} week streak\nGYMFRIEND:${code}`;try{if(navigator.share)await navigator.share({title:'Mijn Gym Journey',text:txt});else{await navigator.clipboard.writeText(txt);toast('Profielcode gekopieerd')}}catch{}}
window.addFriendCode=()=>modal('Vriend toevoegen',`<div class="sub">Plak de GYMFRIEND-code die je vriend heeft gedeeld.</div><textarea id="friendCode" style="width:100%;min-height:130px;margin:10px 0;border:1px solid #d0d5dd;border-radius:11px;padding:10px"></textarea><button class="btn" style="width:100%" onclick="saveFriendCode()">Toevoegen</button>`)
window.saveFriendCode=()=>{try{let raw=friendCode.value.trim(),code=(raw.match(/GYMFRIEND:([A-Za-z0-9+/=]+)/)||[])[1]||raw,p=JSON.parse(decodeURIComponent(escape(atob(code))));if(!p.name||!p.level)throw 0;db.game.friends=db.game.friends.filter(x=>x.name!==p.name);db.game.friends.unshift({...p,addedAt:Date.now()});save();closeModal();renderFriends();toast('👥 Vriend toegevoegd')}catch{alert('Dit is geen geldige profielcode.')}}
function renderFriends(){let el=document.getElementById('friendsList');if(!el)return;let a=db.game.friends||[];el.innerHTML=a.length?a.map((f,i)=>`<div class="friendCard"><div class="between row"><div class="row"><div class="levelBubble">${f.level}</div><div><b>${esc(f.name)}</b><div class="small muted">${esc(f.title||'')} · ⭐ ${(+f.xp||0).toLocaleString('nl-NL')} XP · 🔥 ${f.streak||0}</div></div></div><button class="linkbtn" onclick="removeFriend(${i})">Wis</button></div>${f.badges?.length?`<div class="small" style="margin-top:6px">${f.badges.map(esc).join(' · ')}</div>`:''}${f.last?`<div class="small muted" style="margin-top:5px">Recent: ${esc(f.last.name)} · ${Math.round(f.last.volume||0).toLocaleString('nl-NL')} kg volume</div>`:''}</div>`).join(''):'<div class="muted item">Nog geen vrienden toegevoegd.</div>'}
window.removeFriend=i=>{db.game.friends.splice(i,1);save();renderFriends()}

const MUSCLES=[
 [/incline.*press|incline bench/i,'Upper chest'],[/bench press|chest press|chest fly|cable fly/i,'Borst'],
 [/lateral raise/i,'Side delts'],[/rear delt/i,'Rear delts'],[/shoulder press/i,'Schouders'],
 [/curl/i,'Biceps'],[/tricep|overhead tricep/i,'Triceps'],[/pulldown|pull-up/i,'Lats'],
 [/row/i,'Rug'],[/squat|leg press|leg extension/i,'Quads'],[/romanian|leg curl/i,'Hamstrings'],[/calf/i,'Kuiten']
];
function muscleFor(n){for(let [r,m] of MUSCLES)if(r.test(n))return m;return'Overig'}
function recentCompleted(days=7){let cut=Date.now()-days*864e5;return Object.values(db.workouts).filter(isCompleted).filter(w=>{let t=Date.parse(w.date+'T12:00:00');return t>=cut&&w.date<=today()})}
function renderMuscleVolume(){let el=document.getElementById('muscleVolume');if(!el)return;let x={};recentCompleted(7).forEach(w=>(w.exercises||[]).forEach(e=>{let n=(e.sets||[]).filter(s=>s.done).length;if(n)x[muscleFor(e.name)]=(x[muscleFor(e.name)]||0)+n}));let a=Object.entries(x).sort((a,b)=>b[1]-a[1]);el.innerHTML=a.length?a.map(([m,n])=>`<div class="item between row"><span>${esc(m)}</span><b>${n} sets</b></div>`).join(''):'<div class="muted item">Nog geen sets in de laatste 7 dagen.</div>'}
function allPRs(){let by={},prs=[];Object.values(db.workouts).filter(isCompleted).sort((a,b)=>a.date.localeCompare(b.date)||(+a.finishedAt||0)-(+b.finishedAt||0)).forEach(w=>(w.exercises||[]).forEach(e=>{let id=e.exerciseId||exkey(e.name),best=by[id]||{kg:0,e1:0,repsAtKg:{}};(e.sets||[]).forEach(s=>{let kg=+s.kg||0,r=+s.reps||0;if(!s.done||!kg||!r)return;let e1=kg*(1+r/30),types=[];if(kg>best.kg){types.push('gewicht');best.kg=kg}if(e1>best.e1+0.01){types.push('e1RM');best.e1=e1}if(r>(best.repsAtKg[kg]||0)){if(best.repsAtKg[kg])types.push('reps');best.repsAtKg[kg]=r}if(types.length)prs.push({date:w.date,name:e.name,kg,reps:r,e1,types})});by[id]=best}));return prs}
function weightTrend(){let a=Object.entries(db.days).filter(x=>x[1].weight).sort().slice(-21);if(a.length<4)return null;let half=Math.max(2,Math.floor(a.length/2)),A=a.slice(0,half).map(x=>+x[1].weight),B=a.slice(-half).map(x=>+x[1].weight),av=x=>x.reduce((s,v)=>s+v,0)/x.length,days=Math.max(1,(Date.parse(a.at(-1)[0])-Date.parse(a[0][0]))/864e5);return{perWeek:(av(B)-av(A))*7/(days/2),latest:av(B)}}
function nextLiftAdvice(){let w=getW(),items=[];(w.exercises||[]).forEach(e=>{let p=prev(e.name,w);if(!p)return;let ss=(p.sets||[]).filter(s=>+s.kg&&+s.reps);if(!ss.length)return;let range=String(e.range||'').match(/(\d+)\D+(\d+)/),hi=range?+range[2]:12,lo=range?+range[1]:8,min=Math.min(...ss.map(s=>+s.reps)),kg=Math.max(...ss.map(s=>+s.kg));items.push(min>=hi?`${e.name}: rep-range gehaald → probeer een kleine gewichtsverhoging boven ${kg} kg.`:`${e.name}: probeer ${kg} kg richting ${hi} reps per set.`)});return items[0]||''}
function renderCoach(){let el=document.getElementById('coachText');if(!el)return;let t=weightTrend(),msg,badge='Start';if(!t){msg='Log je gewicht regelmatig. Na meerdere metingen kan ik je trend beoordelen.'}else{let goal=db.calculator?.goal||'lean',r=t.perWeek;if(goal==='lean'){if(r<0.05){badge='Onder tempo';msg=`Je gewichtstrend is ${r>=0?'+':''}${r.toFixed(2)} kg/week. Voor een lean bulk is dat vrij langzaam; houd eerst je gemiddelde inname consistent en overweeg daarna +100 kcal.`}else if(r<=0.30){badge='Op schema';msg=`Je gewichtstrend is +${r.toFixed(2)} kg/week. Dat past bij een rustige bulk; calorieën voorlopig behouden.`}else{badge='Snel';msg=`Je gewichtstrend is +${r.toFixed(2)} kg/week. Dat is relatief snel; overweeg ongeveer 100–150 kcal minder als dit 2 weken aanhoudt.`}}else{badge='Trend';msg=`Je huidige gewichtstrend is ${r>=0?'+':''}${r.toFixed(2)} kg/week.`}}coachBadge.textContent=badge;el.textContent=msg;nextLift.textContent=nextLiftAdvice()||'Na een eerdere training verschijnt hier je volgende progressive-overload doel.';let pc=document.getElementById('progressCoach');if(pc)pc.textContent=msg}
window.openPhotoCompare=async()=>{let a=await allPhotos();if(a.length<2)return alert('Je hebt minimaal 2 progressiefoto’s nodig.');let opts=a.map((p,i)=>`<option value="${i}">${new Date(p.date).toLocaleDateString('nl-NL')}${p.weight?' · '+p.weight+' kg':''}</option>`).join('');modal("Foto's vergelijken",`<div class="grid2"><select id="cmpA">${opts}</select><select id="cmpB">${opts}</select></div><button class="btn" style="width:100%;margin:8px 0" onclick="renderPhotoCompare()">Vergelijk</button><div id="cmpOut"></div>`);cmpB.value=String(a.length-1);window._cmpPhotos=a;renderPhotoCompare()}
window.renderPhotoCompare=()=>{let a=window._cmpPhotos?.[+cmpA.value],b=window._cmpPhotos?.[+cmpB.value];if(!a||!b)return;cmpOut.innerHTML=`<div class="grid2"><div><img src="${a.data}" style="width:100%;border-radius:12px"><div class="small muted">${new Date(a.date).toLocaleDateString('nl-NL')}${a.weight?' · '+a.weight+' kg':''}</div></div><div><img src="${b.data}" style="width:100%;border-radius:12px"><div class="small muted">${new Date(b.date).toLocaleDateString('nl-NL')}${b.weight?' · '+b.weight+' kg':''}</div></div></div>`}

// Scanner V5: ZXing is primary on iOS/Safari, with photo and manual fallbacks.
function wkey(date=today(),name=selected){return date+'|'+name}
function formatWorkoutDate(date){let d=new Date((date||today())+'T12:00:00');return d.toLocaleDateString('nl-NL',{weekday:'long',day:'numeric',month:'long'})}
function exkey(name){return String(name||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\b(machine|cable|dumbbell|barbell|ez[- ]?bar)\b/g,'').replace(/[^a-z0-9]+/g,' ').trim()}
// Rendering returns an unsaved draft; only deliberate input persists it.
function getW(persist=false){let w=Object.values(db.activeSessions).find(w=>w.name===selected);return w||(persist?BulkyCore.start(db,selected):BulkyCore.draft(db,selected))}
function prev(name){return BulkyCore.previous(db,name)}
let renderedWorkoutDate=today();
function ensureWorkoutDay(){return true}
function series(name){let a=[];Object.values(db.workouts).forEach(w=>{let e=w.exercises?.find(x=>x.name===name),s=e?.sets.filter(x=>x.done&&+x.kg&&+x.reps)||[];if(s.length)a.push({date:w.date,kg:Math.max(...s.map(x=>+x.kg)),e1:Math.max(...s.map(x=>+x.kg*(1+(+x.reps)/30))),vol:s.reduce((z,x)=>z+(+x.kg)*(+x.reps),0)})});return a.sort((a,b)=>a.date.localeCompare(b.date))}function lifetimeStats(){let total=0,sessions=0;Object.values(db.workouts).forEach(w=>{let had=w.finished===true;(w.exercises||[]).forEach(e=>(e.sets||[]).forEach(x=>{let kg=+x.kg||0,reps=+x.reps||0;if(x.done&&kg>0&&reps>0){total+=kg*reps;had=true}}));if(had)sessions++});return{total,sessions}}const liftRanks=[{kg:0,n:'Gym Spawn',e:'🥚',d:'De reis begint.'},{kg:25000,n:'IJzerleerling',e:'🔩',d:'Je kent inmiddels de weg naar het squatrek.'},{kg:100000,n:'Plate Collector',e:'🏋️',d:'100 ton verplaatst. De schijven kennen je naam.'},{kg:250000,n:'Forklift Human',e:'🚜',d:'Een kwart miljoen kilo. Officieel heftruckgedrag.'},{kg:500000,n:'Eddie Hall Energy',e:'🦍',d:'Niet letterlijk zo sterk als Eddie Hall — wel 500 ton trainingsvolume.'},{kg:750000,n:'Gravity Negotiator',e:'🛰️',d:'Zwaartekracht is inmiddels een onderhandeling.'},{kg:1000000,n:'Certified Alien',e:'👽',d:'Eén miljoen kilo. Menselijke software, buitenaards volume.'},{kg:2000000,n:'Planet Mover',e:'🪐',d:'Twee miljoen kilo. Tektonische platen worden nerveus.'},{kg:5000000,n:'Final Boss',e:'☄️',d:'De gym vraagt jou inmiddels om rustiger te doen.'}];function renderLifetime(){let s=lifetimeStats(),goal=1000000,p=Math.min(100,s.total/goal*100);let el=document.getElementById('lifetimeTonnage');if(el)el.textContent=Math.round(s.total).toLocaleString('nl-NL')+' kg';if(document.getElementById('millionBar'))millionBar.style.width=p+'%';if(document.getElementById('millionText'))millionText.textContent=p.toFixed(2).replace('.',',')+'% van 1.000.000 kg';if(document.getElementById('sessionCount'))sessionCount.textContent=s.sessions+' trainingen';let cur=liftRanks.filter(r=>s.total>=r.kg).at(-1)||liftRanks[0],next=liftRanks.find(r=>r.kg>s.total);if(document.getElementById('rankBadge'))rankBadge.textContent=cur.e+' '+cur.n;if(document.getElementById('rankNow'))rankNow.textContent=cur.d;if(document.getElementById('rankNext'))rankNext.textContent=next?`${Math.round(next.kg-s.total).toLocaleString('nl-NL')} kg tot ${next.e} ${next.n}`:'Je hebt alle huidige ranks uitgespeeld.';if(document.getElementById('rankList'))rankList.innerHTML=liftRanks.map(r=>`<div class="rank ${s.total>=r.kg?'current':'locked'}"><span>${r.e} <b>${r.n}</b></span><span style="float:right">${r.kg.toLocaleString('nl-NL')} kg</span></div>`).join('')}let workoutCalCursor=new Date();workoutCalCursor.setDate(1);
function workoutsForDate(date){return Object.values(db.workouts).filter(w=>w.date===date).sort((a,b)=>(+b.finishedAt||+b.createdAt||0)-(+a.finishedAt||+a.createdAt||0))}
function workoutForDate(date){return workoutsForDate(date)[0]||null}
function renderWorkoutCalendar(){let label=document.getElementById('workoutCalMonth'),grid=document.getElementById('workoutCalDays');if(!label||!grid)return;let y=workoutCalCursor.getFullYear(),m=workoutCalCursor.getMonth(),first=new Date(y,m,1),last=new Date(y,m+1,0),offset=(first.getDay()+6)%7;label.textContent=first.toLocaleDateString('nl-NL',{month:'long',year:'numeric'});let html='';for(let i=0;i<offset;i++)html+='<button class="calDay empty"></button>';for(let d=1;d<=last.getDate();d++){let dt=new Date(y,m,d),key=localDateKey(dt),ws=workoutsForDate(key),has=plannedWorkouts(key).length>0||ws.length>0,finished=ws.some(isCompleted),cls='calDay'+(has?' hasWorkout':'')+(finished?' finished':'')+(key===today()?' today':'');html+=`<button class="${cls}" onclick="showWorkoutDay('${key}')">${d}${finished?' ✓':''}</button>`}grid.innerHTML=html}
window.changeWorkoutMonth=n=>{workoutCalCursor.setMonth(workoutCalCursor.getMonth()+n);renderWorkoutCalendar()}
function renderProgress(){renderWorkoutCalendar();renderLifetime();renderMuscleVolume();renderPRs();let names=[...new Set(Object.values(db.workouts).flatMap(w=>w.exercises?.map(e=>e.name)||[]).concat(Object.values(db.plans).flat().map(e=>e[0])))].sort(),old=pex.value;pex.innerHTML=names.map(n=>`<option>${esc(n)}</option>`).join('');if(names.includes(old))pex.value=old;loadPhotos().catch(()=>{photos.textContent='Foto-opslag is niet beschikbaar.'});setTimeout(drawCharts,10)}pex.onchange=drawCharts;function line(c,vals,label){let x=c.getContext('2d');x.clearRect(0,0,c.width,c.height);if(vals.length<2){x.fillStyle='#667085';x.font='13px system-ui';x.fillText('Minimaal 2 metingen nodig voor een grafiek.',12,85);return}let mn=Math.min(...vals),mx=Math.max(...vals);if(mx===mn)mx++;let p=24;x.strokeStyle='#101827';x.lineWidth=3;x.beginPath();vals.forEach((v,i)=>{let px=p+i*(c.width-2*p)/(vals.length-1),py=c.height-p-(v-mn)/(mx-mn)*(c.height-2*p);i?x.lineTo(px,py):x.moveTo(px,py)});x.stroke();x.fillStyle='#667085';x.font='12px system-ui';x.fillText(label,8,16)}function drawCharts(){let weights=Object.entries(db.days).filter(x=>x[1].weight).sort().slice(-20).map(x=>+x[1].weight);line(weightChart,weights,weights.length?'Laatste '+weights.at(-1).toFixed(1)+' kg':'');let s=series(pex.value);bestkg.textContent=s.length?Math.max(...s.map(x=>x.kg)).toFixed(1)+' kg':'—';best1.textContent=s.length?Math.max(...s.map(x=>x.e1)).toFixed(1)+' kg':'—';vol.textContent=s.length?Math.round(s.at(-1).vol)+' kg':'—';line(strengthChart,s.map(x=>x.e1),s.length?'e1RM '+s.at(-1).e1.toFixed(1)+' kg':'')}
// Photos in IndexedDB, separate from localStorage because images are larger.
let idb;function openIDB(){return new Promise((res,rej)=>{let r=indexedDB.open('leanbulk_media',1);r.onupgradeneeded=()=>r.result.createObjectStore('photos',{keyPath:'id'});r.onsuccess=()=>{idb=r.result;res(idb)};r.onerror=()=>rej(r.error)})}async function allPhotos(){await openIDB();return new Promise((res,rej)=>{let r=idb.transaction('photos').objectStore('photos').getAll();r.onsuccess=()=>res(r.result.sort((a,b)=>b.date.localeCompare(a.date)));r.onerror=()=>rej(r.error)})}async function loadPhotos(){let a=await allPhotos();photos.innerHTML=a.length?a.map(p=>`<img class="photo" src="${p.data}" onclick="showPhoto('${p.id}')">`).join(''):'<div class="muted item">Nog geen foto\'s.</div>';}photoInput.onchange=async()=>{let f=photoInput.files[0];if(!f)return;let data=await resizeImage(f,1100,.78);await openIDB();idb.transaction('photos','readwrite').objectStore('photos').put({id:crypto.randomUUID(),date:new Date().toISOString(),weight:day().weight||null,data});loadPhotos();photoInput.value=''};function resizeImage(f,max,q){return new Promise(res=>{let im=new Image(),u=URL.createObjectURL(f);im.onload=()=>{let s=Math.min(1,max/Math.max(im.width,im.height)),c=document.createElement('canvas');c.width=im.width*s;c.height=im.height*s;c.getContext('2d').drawImage(im,0,0,c.width,c.height);URL.revokeObjectURL(u);res(c.toDataURL('image/jpeg',q))};im.src=u})}window.showPhoto=async id=>{let a=await allPhotos(),p=a.find(x=>x.id===id);modal('Progressiefoto',`<img src="${p.data}" style="width:100%;border-radius:14px"><div class="sub" style="margin:8px 0">${new Date(p.date).toLocaleDateString('nl-NL')} ${p.weight?'· '+p.weight+' kg':''}</div><button class="btn danger" onclick="deletePhoto('${id}')">Foto verwijderen</button>`)};window.deletePhoto=async id=>{await openIDB();idb.transaction('photos','readwrite').objectStore('photos').delete(id);closeModal();loadPhotos()};
window.exportAll=async()=>{let ps=await allPhotos(),payload={app:'Bulky',version:V,exported:new Date().toISOString(),data:db,photos:ps};let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(payload)],{type:'application/json'}));a.download='bulky-volledige-backup-'+today()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};function decimal(value){let s=String(value??'').trim().replace(',','.');return /^\d+(\.\d+)?$/.test(s)?Number(s):NaN}
function foodUnit(p){return p.type==='100g'?'g':p.type==='100ml'?'ml':p.unit||'stuk'}
function mealProduct(it){return it.product||db.products[it.productId]}
let mealDraft=[];
window.openMealEditor=(id='')=>{let m=id?db.meals[id]:{name:'',items:[]};mealDraft=clone(m.items||[]);modal(id?'Maaltijd aanpassen':'Nieuwe maaltijd',`<div class="field"><label>Naam maaltijd</label><input id="mn" value="${esc(m.name)}" placeholder="Mijn bord pap"></div><div class="sub">De ingrediënten hieronder vormen samen 1 maaltijd. Voer bijvoorbeeld 0,7 × 100 g Brinta en 3 × 100 ml melk in.</div><div id="mealParts"></div><button class="btn sec" style="width:100%;margin:10px 0" onclick="addMealPart()">+ Ingrediënt</button><div id="mealPreview" class="notice" aria-live="polite"></div><button class="btn" style="width:100%;margin-top:12px" onclick="saveMeal('${esc(id)}')">Maaltijd opslaan</button>`);if(!mealDraft.length)addMealPart();else renderMealParts()};
function renderMealParts(){mealParts.innerHTML=mealDraft.map((it,i)=>{let p=mealProduct(it),opts=Object.values(db.products).map(x=>`<option value="${esc(x.id)}" ${x.id===it.productId?'selected':''}>${esc(x.name)}</option>`).join('');if(!db.products[it.productId])opts=`<option value="${esc(it.productId||'')}" selected>${esc(p?.name||'Kies een product')}</option>`+opts;let mode=it.mode||'factor',qty=it.input??(p?.type==='unit'||mode==='amount'?it.qty:it.qty/100);return `<div class="item"><label>Ingrediënt ${i+1}</label><select style="width:100%" onchange="changeMealProduct(${i},this.value)">${opts}</select>${p?`<div class="qtyrow"><select onchange="changeMealMode(${i},this.value)">${quantityModes(p,mode)}</select><input aria-label="Hoeveelheid ingrediënt ${i+1}" type="text" inputmode="decimal" value="${esc(qty)}" oninput="changeMealQuantity(${i},this.value)"></div><div class="small muted">Basis: ${esc(p.name)}, per ${p.type==='unit'?'1':'100'} ${esc(foodUnit(p))}</div>`:''}<button class="linkbtn" onclick="removeMealPart(${i})">Verwijder ingrediënt</button></div>`}).join('');previewMeal()}
window.addMealPart=()=>{let p=Object.values(db.products)[0];if(!p)return alert('Voeg eerst een product toe via Producten, bijvoorbeeld Brinta met waarden per 100 g.');mealDraft.push({productId:p.id,product:clone(p),qty:p.type==='unit'?1:100});renderMealParts()};
window.removeMealPart=i=>{mealDraft.splice(i,1);renderMealParts()};
window.changeMealProduct=(i,id)=>{let p=db.products[id];if(!p)return;mealDraft[i]={productId:id,product:clone(p),qty:p.type==='unit'?1:100};renderMealParts()};
window.changeMealQuantity=(i,value)=>{let it=mealDraft[i];it.input=value;try{it.qty=foodQuantity(mealProduct(it),value,it.mode||'factor')}catch{it.qty=null}previewMeal()};
window.changeMealMode=(i,mode)=>{let it=mealDraft[i],p=mealProduct(it);it.mode=mode;it.input=it.qty==null?'':mode==='factor'&&p.type!=='unit'?it.qty/100:it.qty;renderMealParts()};
function previewMeal(){try{mealPreview.innerHTML='Totaal voor 1 maaltijd<br>'+foodSummary(mealTotals(mealDraft))}catch(e){mealPreview.textContent=e.message}}
window.saveMeal=id=>{try{mealTotals(mealDraft);let name=mn.value.trim();if(!name)throw Error('Geef je maaltijd een naam.');let items=mealDraft.map(it=>({productId:it.productId,qty:it.qty,product:clone(mealProduct(it))})),nid=id||crypto.randomUUID();db.meals[nid]={id:nid,name,items};save();closeModal();render()}catch(e){alert(e.message)}};


