const R=BulkyReliable;
function nutrientText121(v){return v===null||v===undefined?'onbekend':Number(v).toLocaleString('nl-NL',{maximumFractionDigits:1})}
function foodTotals(p,q){return R.totals(R.source(p),q)}
function foodQuantity(p,v,mode){return R.quantity(p,v,mode)}
function foodSummary(t){return `<b>${nutrientText121(t.kcal)} kcal</b> · ${nutrientText121(t.protein)} g eiwit · ${nutrientText121(t.carbs)} g koolhydraten · ${nutrientText121(t.fat)} g vet`}
function mealTotals(items,multiple=1){R.positive(multiple);if(!items.length)throw Error('Voeg een ingrediënt toe.');const t={kcal:0,protein:0,carbs:0,fat:0};for(const it of items){const p=mealProduct(it);if(!p)throw Error('Een ingrediënt ontbreekt. Kies een vervangend product.');const v=foodTotals(p,R.positive(it.qty)*multiple);for(const k of R.keys)t[k]=t[k]===null||v[k]===null?null:t[k]+v[k]}return t}
function quantityModes(p,mode='amount'){return `<option value="amount" ${mode==='amount'?'selected':''}>${p.type==='unit'?'Aantal '+esc(p.unit||'porties'):'Hoeveelheid in '+foodUnit(p)}</option>${p.type!=='unit'?`<option value="factor" ${mode==='factor'?'selected':''}>Aantal × 100 ${foodUnit(p)}</option>`:''}${p.serving>0?`<option value="serving" ${mode==='serving'?'selected':''}>Porties van ${esc(p.serving)} ${esc(foodUnit(p))}</option>`:''}`}
let foodDraft121=null,search121={seq:0,items:[],q:'',error:'',controller:null},foodEdit121=null;
const categories121=['Ontbijt','Lunch','Avondeten','Tussendoor','Overig'];
function categorySelect121(value='Overig'){return `<label>Maaltijdcategorie<select id="foodCategory121">${categories121.map(v=>`<option ${v===value?'selected':''}>${v}</option>`).join('')}</select></label>`}
function openFood121(p,{date=today(),id=crypto.randomUUID(),back=false,recipe=null}={}){foodDraft121={p:clone(p),date,id,back,recipe,committed:false};closeSearch121();modal(p.name,`<p>${esc(p.brand||'')}</p><div class="notice">Waarden per ${p.type==='unit'?'1 '+esc(p.unit||'portie'):'100 '+foodUnit(p)}. ${esc(p.basisNote||'')}${!p.serving&&p.type!=='unit'?'<br>Portiegrootte onbekend: gebruik g/ml of ×100.':''}</div><div class="field"><label>Eenheid<select id="lmode" onchange="switchProductMode()">${quantityModes(p)}</select></label></div><div class="field"><label>Hoeveelheid<input id="lqty" inputmode="decimal" value="${p.type==='unit'?1:100}" oninput="previewProduct()"></label></div>${categorySelect121()}<div id="portionPreview" class="notice" aria-live="polite"></div><button class="btn full" id="foodCommit121" onclick="commitProduct()">Toevoegen aan ${esc(formatWorkoutDate(date))}</button>${p.origin==='Open Food Facts'?'<button class="btn sec full" onclick="editSelectedProduct121()">Etiket controleren / product bewaren</button>':''}${back?'<button class="btn sec full" onclick="backToSearch121()">Terug naar zoekresultaten</button>':''}`);lmode.value='amount';lmode.dataset.previous='amount';previewProduct()}
window.logProduct=id=>{if(db.products[id])openFood121(db.products[id])};
window.switchProductMode=()=>{const p=foodDraft121.p;try{const q=foodQuantity(p,lqty.value,lmode.dataset.previous);lqty.value=lmode.value==='factor'&&p.type!=='unit'?q/100:lmode.value==='serving'?q/p.serving:q}catch{}lmode.dataset.previous=lmode.value;previewProduct()};
window.previewProduct=()=>{if(!foodDraft121)return;try{const p=foodDraft121.p,q=foodQuantity(p,lqty.value,lmode.value);portionPreview.innerHTML=`${nutrientText121(q)} ${esc(foodUnit(p))}<br>${foodSummary(foodTotals(p,q))}`;foodCommit121.disabled=false}catch(e){portionPreview.textContent=e.message;foodCommit121.disabled=true}};
window.commitProduct=()=>{const draft=foodDraft121;if(!draft||draft.committed)return;try{const q=foodQuantity(draft.p,lqty.value,lmode.value),log=R.makeLog(draft.p,q,{id:draft.id,date:draft.date,category:foodCategory121.value});if(draft.recipe)log.recipeSnapshot=clone(draft.recipe);const d=BulkyCore.ensureDay(db,draft.date);if(d.foods.some(f=>f.id===draft.id))return;d.foods.push(log);try{save()}catch(e){d.foods.pop();throw e}draft.committed=true;catalogQuery.value='';search121.seq++;search121.items=[];catalogResults.innerHTML='';closeModal();render()}catch(e){alert(e.message)}};
window.logMeal=id=>{try{const m=db.meals[id],t=mealTotals(m.items);openFood121({name:m.name,type:'unit',unit:'maaltijd',...t},{recipe:m.items})}catch(e){alert(e.message)}};
window.commitMeal=()=>commitProduct();
function openFoodLog121(date,id){const log=db.days[date]?.foods.find(f=>f.id===id);if(!log)return;foodEdit121={date,id};modal(log.name,`<p>${esc(log.brand||'')} · ${esc(fullDate(date))} · ${esc(log.category||'Overig')}</p><p>${esc(log.qtyLabel||'Hoeveelheid onbekend')}</p><p>${foodSummary(log)}</p><p>Eenheid: ${esc(log.unit||'onbekend')}; portiegrootte: ${log.source?.serving?esc(log.source.serving)+' '+esc(log.unit):'onbekend'}</p>${log.legacy?'<div class="notice">Oude log zonder oorspronkelijke bronhoeveelheid. Bewerken kan als veelvoud van deze oorspronkelijke log; gramwaarden worden niet geraden.</div>':''}<button class="btn full" onclick="editFoodLog121()">Hoeveelheid / portie bewerken</button><button class="btn sec full" onclick="deleteFoodLog121()">Verwijderen</button>`)}
function editFoodLog121(){const {date,id}=foodEdit121,log=db.days[date]?.foods.find(f=>f.id===id);if(!log)return;modal('Voedingslog bewerken',`<p>${esc(log.name)} · ${esc(fullDate(date))}</p><label>Eenheid<select id="editMode121" onchange="switchEdit121()">${quantityModes(log.source)}</select></label><label>Hoeveelheid<input id="editQty121" inputmode="decimal" value="${log.amount}" oninput="previewEdit121()"></label>${categorySelect121(log.category)}<div id="editPreview121" class="notice" aria-live="polite"></div><button class="btn full" onclick="saveFoodEdit121()">Wijziging opslaan op deze dag</button>`);editMode121.value='amount';editMode121.dataset.previous='amount';previewEdit121()}
function switchEdit121(){const {date,id}=foodEdit121,log=db.days[date].foods.find(f=>f.id===id);try{const q=foodQuantity(log.source,editQty121.value,editMode121.dataset.previous);editQty121.value=editMode121.value==='serving'?q/log.source.serving:editMode121.value==='factor'&&log.source.type!=='unit'?q/100:q}catch{}editMode121.dataset.previous=editMode121.value;previewEdit121()}
function previewEdit121(){try{const {date,id}=foodEdit121,log=db.days[date].foods.find(f=>f.id===id);editPreview121.innerHTML=foodSummary(R.totals(log.source,foodQuantity(log.source,editQty121.value,editMode121.value)))}catch(e){editPreview121.textContent=e.message}}
function saveFoodEdit121(){if(!foodEdit121)return;try{const {date,id}=foodEdit121,d=db.days[date],i=d.foods.findIndex(f=>f.id===id);if(i<0)return;const old=d.foods[i],q=foodQuantity(old.source,editQty121.value,editMode121.value);d.foods[i]=R.editLog(old,q,foodCategory121.value);try{save()}catch(e){d.foods[i]=old;throw e}foodEdit121=null;closeModal();render()}catch(e){alert(e.message)}}
function deleteFoodLog121(){if(!foodEdit121)return;const {date,id}=foodEdit121,d=db.days[date],i=d.foods.findIndex(f=>f.id===id);if(i<0||!confirm('Deze voedingslog op '+fullDate(date)+' verwijderen?'))return;const old=d.foods.splice(i,1)[0];try{save()}catch(e){d.foods.splice(i,0,old);return}foodEdit121=null;closeModal();render()}
window.delFood=i=>openFoodLog121(today(),day().foods[i]?.id);
function renderLibrary(){productList.innerHTML=Object.values(db.products).map(p=>`<div class="item"><b>${esc(p.name)}</b><div class="sub">${foodSummary(p)} per ${p.type==='unit'?'1 '+esc(p.unit||'portie'):'100 '+foodUnit(p)}</div><div class="row"><button class="linkbtn" onclick="logProduct(${argument(p.id)})">Loggen</button><button class="linkbtn" onclick="openProductEditor(${argument(p.id)})">Wijzigen</button><button class="linkbtn" onclick="deleteProduct(${argument(p.id)})">Wissen</button></div></div>`).join('')||'<p>Nog geen eigen producten.</p>';mealList.innerHTML=Object.values(db.meals).map(m=>`<div class="item between row"><b>${esc(m.name)}</b><button class="linkbtn" onclick="logMeal(${argument(m.id)})">Loggen</button><button class="linkbtn" onclick="openMealEditor(${argument(m.id)})">Wijzigen</button></div>`).join('')||'<p>Maak je eerste maaltijd.</p>'}
window.saveProduct=id=>{const values={};for(const [k,input] of Object.entries({kcal:pk,protein:pp,carbs:pc,fat:pf})){const v=input.value.trim();if(v!==''&&R.number(v)===null)return alert('Gebruik een positief getal, nul of laat onbekende waarden leeg.');values[k]=R.number(v)}const name=pn.value.trim();if(!name)return alert('Vul een productnaam in.');const serv=pserv.value.trim();if(serv&&!(R.number(serv)>0))return alert('Controleer de portiegrootte.');const nid=id||crypto.randomUUID();db.products[nid]={...db.products[id],id:nid,name,type:ptype.value,unit:punit.value.trim()||'portie',barcode:pb.value.trim(),...values,serving:R.number(serv),servingName:pservname.value.trim()};save();closeModal();render()};
const originalProductForm121=productForm;productForm=(p={},code='')=>originalProductForm121(p,code)+'<p class="sub">Leeg = onbekend. Vul 0 uitsluitend in wanneer het etiket echt nul aangeeft. Portiegewicht moet dezelfde eenheid gebruiken als de bron (g of ml).</p>';
function closeSearch121(){search121.seq++;search121.controller?.abort();catalogResults.innerHTML='';catalogResults.hidden=true}
function searchRows121(){const suggestion=['kaas','oude kaas','banaan','melk','brood'].find(q=>R.norm(search121.q)!==q&&R.near(R.norm(search121.q),q));catalogResults.hidden=false;catalogResults.innerHTML=(search121.error?`<div class="notice">${esc(search121.error)}</div>`:'')+(suggestion?`<button class="btn sec full" onclick="searchSuggested121(${argument(suggestion)})">Bedoel je ${esc(suggestion)}?</button>`:'')+search121.items.map((p,i)=>`<button class="result foodResult121" onclick="selectResult121(${i})"><span><b>${esc(p.name)}</b><span class="sub">${esc(p.brand||'')} · ${p.localId?'Eigen product':'Open Food Facts'}<br>${foodSummary(p)} / ${p.type==='100ml'?'100 ml':p.type==='unit'?'1 '+esc(p.unit):'100 g'}</span></span></button>`).join('')+`<div class="item"><button class="btn sec full" onclick="searchCatalog(true)">Breder zoeken (ook samengestelde producten)</button><a href="https://nl.openfoodfacts.org/cgi/search.pl?search_terms=${encodeURIComponent(search121.q)}&search_simple=1&action=process" target="_blank" rel="noopener">Zoek rechtstreeks op Open Food Facts</a><button class="btn sec full" onclick="openProductEditor()">Eigen product van het etiket invoeren</button></div>`}
function selectResult121(i){const p=search121.items[i];if(p)openFood121(p,{back:true})}
function backToSearch121(){closeModal();go('library');catalogQuery.value=search121.q;searchRows121()}
const OFF_FIELDS121='code,product_name,product_name_nl,generic_name,generic_name_nl,brands,nutriments,nutrition_data_per,serving_quantity,serving_size,categories';
async function requestJSON121(url,controller=new AbortController()){const timeout=setTimeout(()=>controller.abort(),14000);try{const r=await fetch(url,{signal:controller.signal});if(!r.ok)throw Error(r.status===429?'Zoeklimiet bereikt. Probeer het over een minuut opnieuw.':'Bron niet bereikbaar ('+r.status+').');return await r.json()}finally{clearTimeout(timeout)}}
window.searchCatalog=async(broad=false)=>{const q=catalogQuery.value.trim();if(q.length<2)return;search121.controller?.abort();const seq=++search121.seq;search121.q=q;search121.error='';search121.items=Object.values(db.products).map(p=>({...p,localId:p.id})).filter(p=>R.rank(p,q)>0).sort((a,b)=>R.rank(b,q)-R.rank(a,q));searchRows121();catalogResults.insertAdjacentHTML('afterbegin','<p id="searchLoading121" role="status">Open Food Facts doorzoeken…</p>');const controller=new AbortController();search121.controller=controller;try{db.searchCache121 ||= {};const queryKey=R.norm(q),category=!broad?({'kaas':'en:cheeses','oude kaas':'en:cheeses','melk':'en:milks','brood':'en:breads','banaan':'en:bananas'}[queryKey]):null,key=queryKey+(category?':'+category:''),cache=db.searchCache121[key];let remote;if(cache&&Date.now()-cache.at<864e5)remote=cache.items;else{const url='https://nl.openfoodfacts.org/cgi/search.pl?'+new URLSearchParams({search_terms:q,search_simple:'1',action:'process',json:'1',lc:'nl',page_size:'40',fields:OFF_FIELDS121,...(category?{tagtype_0:'categories',tag_contains_0:'contains',tag_0:category}:{})});const data=await requestJSON121(url,controller);if(!Array.isArray(data.products))throw Error('De bron gaf geen geldige resultaten.');remote=data.products.map(x=>R.off(x));if(seq!==search121.seq)return;if(remote.length){db.searchCache121[key]={at:Date.now(),items:remote};const cacheKeys=Object.keys(db.searchCache121);if(cacheKeys.length>30)delete db.searchCache121[cacheKeys[0]];save()}}if(seq!==search121.seq)return;const seen=new Set(search121.items.map(p=>p.barcode).filter(Boolean));search121.items.push(...remote.filter(p=>!p.barcode||!seen.has(p.barcode)));search121.items.sort((a,b)=>(R.rank(b,q)+(b.localId?8:0))-(R.rank(a,q)+(a.localId?8:0)));if(!search121.items.length)search121.error='Geen resultaten gevonden. Probeer een korter woord of de alternatieve zoekroute hieronder.'}catch(e){if(seq!==search121.seq)return;search121.error=e.name==='AbortError'?'De zoekbron reageert niet op tijd. Eigen producten blijven beschikbaar.':e.message+' Eigen producten blijven beschikbaar.'}if(seq===search121.seq)searchRows121()};
window.openCatalogSearch=()=>{closeModal();go('library');catalogQuery.focus()};
catalogQuery.addEventListener('keydown',e=>{if(e.key==='Enter')searchCatalog()});

function editSelectedProduct121(){if(foodDraft121)modal('Controleer bronwaarden',productForm(foodDraft121.p,foodDraft121.p.barcode))}

function searchSuggested121(q){catalogQuery.value=q;searchCatalog()}
