/* v12.1 pure helpers: nutrition snapshots, migration, timer, selected records. */
(function(root){'use strict';
const copy=x=>JSON.parse(JSON.stringify(x)),keys=['kcal','protein','carbs','fat'];
function number(v){if(v===null||v===undefined||String(v).trim()==='')return null;const s=String(v).trim().replace(',','.');if(!/^\d+(\.\d+)?$/.test(s))return null;const n=Number(s);return Number.isFinite(n)?n:null}
function positive(v){const n=number(v);if(n===null||n<=0)throw Error('Vul een hoeveelheid groter dan nul in, bijvoorbeeld 0,7.');return n}
function level(score){const s=Math.max(0,Math.min(100,Math.round(Number(score)||0)));return s<=20?1:s<=40?2:s<=60?3:s<=80?4:5}
function source(p){const type=['100g','100ml','unit'].includes(p.type)?p.type:'100g';return {name:String(p.name||'Product'),brand:String(p.brand||''),type,unit:type==='100g'?'g':type==='100ml'?'ml':String(p.unit||'portie'),base:type==='unit'?1:100,serving:number(p.serving),servingName:String(p.servingName||p.servingSize||''),barcode:String(p.barcode||''),...Object.fromEntries(keys.map(k=>[k,number(p[k])])),origin:p.origin||'eigen'}}
function quantity(p,input,mode){const q=positive(input);if(mode==='serving'){if(!(number(p.serving)>0))throw Error('Portiegrootte onbekend. Gebruik gram of ml volgens het etiket.');return q*Number(p.serving)}return mode==='factor'&&p.type!=='unit'?q*100:q}
function totals(p,amount){const q=positive(amount),base=p.base||(p.type==='unit'?1:100);return Object.fromEntries(keys.map(k=>{const v=number(p[k]);return [k,v===null?null:v*q/base]}))}
function makeLog(p,amount,{id,date,category='Overig'}={}){const s=source(p),q=positive(amount);return {id:id||crypto.randomUUID(),date,name:s.name,brand:s.brand,source:s,amount:q,unit:s.unit,category,qtyLabel:q.toLocaleString('nl-NL')+' '+s.unit,...totals(s,q)}}
function editLog(log,q,category){const next=copy(log);next.amount=positive(q);next.category=category||log.category||'Overig';Object.assign(next,totals(next.source,next.amount));next.qtyLabel=next.amount.toLocaleString('nl-NL')+' '+next.unit;return next}
function migrate(db){
 db.prFavorites=Array.isArray(db.prFavorites)?[...new Set(db.prFavorites.filter(x=>typeof x==='string'))]:[];
 if(!db.profile||typeof db.profile!=='object')db.profile={name:'',creatineGoal:5};
 if(db.profile.onboardingCompleted===undefined){const meaningful=Object.values(db.days||{}).some(d=>(d.foods||[]).length||d.weight||d.creatine)||Object.keys(db.workouts||{}).length||Object.keys(db.activeSessions||{}).length;db.profile.onboardingCompleted=!!(db.profile.onboarded||String(db.profile.name||'').trim()||meaningful)}
 for(const [date,d] of Object.entries(db.days||{})){const used=new Set();(d.foods||[]).forEach((f,i)=>{if(!f.id||used.has(f.id)){f.id='food:'+date+':'+i;while(used.has(f.id))f.id+=':legacy'}used.add(f.id);f.date=date;f.category ||= 'Overig';if(!f.source){f.legacy=true;f.source={name:f.name,brand:f.brand||'',type:'unit',unit:'oorspronkelijke log',base:1,...Object.fromEntries(keys.map(k=>[k,number(f[k])]))};f.amount=1;f.unit='oorspronkelijke log';/* Never infer gram quantities or product identity from display text. */}})}
 db.nutritionVersion=2;return db;
}
const norm=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim();
function near(a,b){if(Math.abs(a.length-b.length)>1)return false;let i=0,j=0,n=0;while(i<a.length&&j<b.length){if(a[i]===b[j]){i++;j++;continue}if(++n>1)return false;if(a.length>=b.length)i++;if(b.length>=a.length)j++}return n+(i<a.length||j<b.length?1:0)<=1}
function rank(p,q){const query=norm(q),name=norm(p.name),all=norm([p.name,p.brand,p.categories].join(' ')),terms=query.split(' ').filter(Boolean);if(!terms.length)return 0;let score=0;for(const term of terms){if(name.split(' ').includes(term))score+=50;else if(name.includes(term))score+=30;else if(all.includes(term))score+=15;else if(term.length>=4&&all.split(' ').some(w=>near(w,term)))score+=8;else return 0}if(name===query)score+=100;else if(name.startsWith(query))score+=30;return score}
function off(x){if(!x||typeof x!=='object')throw Error('Ongeldig product');const n=x.nutriments||{},basis=String(x.nutrition_data_per||''),serv=String(x.serving_size||''),isMl=/100\s*ml/i.test(basis);let kcal=number(n['energy-kcal_100g']);if(kcal===null&&number(n.energy_100g)!==null&&n.energy_unit==='kJ')kcal=number(n.energy_100g)/4.184;const type=isMl?'100ml':'100g';const servingMatch=serv.match(/([\d.,]+)\s*(g|ml)\b/i),serving=servingMatch&&servingMatch[2].toLowerCase()===(isMl?'ml':'g')?number(servingMatch[1]):null;return {name:String(x.product_name_nl||x.product_name||x.generic_name_nl||x.generic_name||x.brands||'Onbekend product').slice(0,250),brand:String(x.brands||'').slice(0,250),barcode:String(x.code||''),type,unit:isMl?'ml':'g',kcal,protein:number(n.proteins_100g),carbs:number(n.carbohydrates_100g),fat:number(n.fat_100g),serving,servingSize:serv.slice(0,120),categories:String(x.categories||'').slice(0,1000),origin:'Open Food Facts',basisNote:isMl?'Volgens volumebasis van bron':'Bronwaarden per 100 g; controleer etiket bij vloeistoffen',sourceUrl:'https://world.openfoodfacts.org/product/'+encodeURIComponent(x.code||'')}}
function records(db,name){const key=norm(name),rows=[];for(const w of Object.values(db.workouts||{})){if(w.finished!==true)continue;for(const e of w.exercises||[]){if(norm(e.name)!==key)continue;const sets=(e.sets||[]).filter(s=>s.done&&number(s.kg)!==null&&number(s.reps)>0);if(sets.length)rows.push({date:w.date,id:w.id,at:w.finishedAt||0,sets:sets.map(s=>({kg:number(s.kg),reps:number(s.reps),e1:number(s.kg)*(1+number(s.reps)/30)}))})}}rows.sort((a,b)=>a.date.localeCompare(b.date)||a.at-b.at);const sets=rows.flatMap(r=>r.sets);return {rows,weight:sets.length?Math.max(...sets.map(s=>s.kg)):null,best:sets.sort((a,b)=>b.e1-a.e1)[0]||null}}
function remaining(timer,now=Date.now()){return !timer?0:timer.status==='paused'?Math.max(0,timer.remainingMs||0):Math.max(0,(timer.endAt||0)-now)}
function barcode(raw){const code=String(raw||'').replace(/[\s-]/g,'');if(!/^\d+$/.test(code)||![8,12,13,14].includes(code.length))throw Error('Gebruik 8, 12, 13 of 14 cijfers (EAN/UPC/GTIN).');function valid(s){let sum=0;for(let i=s.length-2,w=3;i>=0;i--,w=w===3?1:3)sum+=+s[i]*w;return (10-sum%10)%10===+s.at(-1)}if(valid(code))return code;
 // UPC-E: number system + six compressed digits + check digit.
 if(code.length===8&&/^[01]/.test(code)){const ns=code[0],d=code.slice(1,7),last=d[5];let expanded;if('012'.includes(last))expanded=ns+d.slice(0,2)+last+'0000'+d.slice(2,5);else if(last==='3')expanded=ns+d.slice(0,3)+'00000'+d.slice(3,5);else if(last==='4')expanded=ns+d.slice(0,4)+'00000'+d[4];else expanded=ns+d.slice(0,5)+'0000'+last;expanded+=code[7];if(valid(expanded))return expanded}throw Error('Het controlecijfer klopt niet. Controleer de cijfers onder de barcode.')}
const api={keys,number,positive,level,source,quantity,totals,makeLog,editLog,migrate,norm,near,rank,off,records,remaining,barcode};root.BulkyReliable=api;if(typeof module!=='undefined')module.exports=api;
})(globalThis);
