/* One owning session per camera. Late promises can never adopt a cancelled stream. */
(function(root){
class CameraSession121{
 constructor({media,getReader,getDetector,onResult,onError}){Object.assign(this,{media,getReader,getDetector,onResult,onError});this.current=null;this.serial=0}
 stop(){const s=this.current;this.current=null;++this.serial;if(!s)return;s.cancelled=true;clearTimeout(s.timer);try{s.controls?.stop()}catch{}s.stream?.getTracks().forEach(t=>t.stop());try{s.video.pause();s.video.srcObject=null}catch{}}
 async start(video){this.stop();const s={token:++this.serial,video,cancelled:false,accepted:false};this.current=s;const live=()=>this.current===s&&!s.cancelled;const accept=(code,controls)=>{if(!live()||s.accepted){try{controls?.stop()}catch{}return}s.accepted=true;try{controls?.stop()}catch{}this.stop();this.onResult(code)};
 try{if(!this.media?.getUserMedia)throw Error('Camera vereist HTTPS en toestemming.');const stream=await this.media.getUserMedia({audio:false,video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:720}}});if(!live()){stream.getTracks().forEach(t=>t.stop());return}s.stream=stream;for(const track of stream.getVideoTracks?.()||[]){track.addEventListener?.('ended',()=>{if(live()){this.stop();this.onError(Error('Camera gestopt. Tik op Camera opnieuw starten.'))}});try{if(track.getCapabilities?.().focusMode?.includes('continuous'))await track.applyConstraints({advanced:[{focusMode:'continuous'}]})}catch{}}if(!live())return;video.muted=true;video.setAttribute('playsinline','');video.srcObject=stream;await video.play();if(!live())return;
 let detector=null;try{detector=await this.getDetector?.()}catch{}if(!live())return;
 const zxing=async()=>{if(!live())return;const reader=this.getReader();s.reader=reader;const controls=await reader.decodeFromStream(stream,video,(result,error,c)=>{if(result)accept(result.getText(),c)});if(!live())controls?.stop();else s.controls=controls};
 if(detector){let failures=0;const loop=async()=>{if(!live())return;try{const results=await detector.detect(video);if(!live())return;if(results?.[0]?.rawValue){accept(results[0].rawValue);return}failures=0}catch{if(++failures>=3){try{await zxing()}catch(e){if(live()){this.stop();this.onError(e)}}return}}if(live())s.timer=setTimeout(loop,150)};loop()}else await zxing();
 }catch(e){if(live()){this.stop();this.onError(e)}}}
}
root.CameraSession121=CameraSession121;if(typeof module!=='undefined')module.exports=CameraSession121;
})(globalThis);
if(typeof document!=='undefined'){
var requestView121=0,barcodeRequest121=null,barcodePhotoURL121=null;
var scanner121=new CameraSession121({media:navigator.mediaDevices,getReader:()=>{if(!window.ZXingBrowser)throw Error('Lokale scannerbibliotheek ontbreekt. Upload de volledige bundel.');return new ZXingBrowser.BrowserMultiFormatReader(undefined,{delayBetweenScanAttempts:120,delayBetweenScanSuccess:500})},getDetector:async()=>{if(!window.BarcodeDetector)return null;const available=await BarcodeDetector.getSupportedFormats(),formats=['ean_13','ean_8','upc_a','upc_e','itf'].filter(x=>available.includes(x));return formats.length?new BarcodeDetector({formats}):null},onResult:code=>{try{lookupBarcode(R.barcode(code))}catch(e){manualBarcode(code,e.message)}},onError:e=>{const msg=document.getElementById('scanmsg');if(msg)msg.textContent=e.name==='NotAllowedError'?'Cameratoegang geweigerd. Sta camera toe in Safari/website-instellingen of voer de barcode handmatig in.':e.name==='NotReadableError'?'Camera bezet. Sluit andere cameratoepassingen en probeer opnieuw.':e.message||'Camera niet beschikbaar. Gebruik handmatige invoer.'}});
var plainModal121=modal;modal=(title,html)=>{scanner121.stop();barcodeRequest121?.abort();requestView121++;plainModal121(title,html)};
window.closeModal=()=>{scanner121.stop();barcodeRequest121?.abort();requestView121++;if(barcodePhotoURL121){URL.revokeObjectURL(barcodePhotoURL121);barcodePhotoURL121=null}document.getElementById('modal').classList.remove('on')};
window.stopScan=()=>scanner121.stop();
window.startScan=()=>{modal('Barcode scannen',`<p class="sub">Houd de hele streepjescode scherp in beeld. Beweeg rustig verder weg als de camera niet scherpstelt.</p><video id="scanvideo" playsinline muted autoplay style="width:100%;height:260px;object-fit:cover;background:#14241b;border-radius:16px"></video><p id="scanmsg" role="status">Camera openen…</p><button class="btn sec full" onclick="startScan()">Camera opnieuw starten</button><button class="btn full" onclick="manualBarcode()">Barcode handmatig invoeren</button><button class="btn sec full" onclick="barcodePhoto121.click()">Barcode uit foto lezen</button><input hidden id="barcodePhoto121" type="file" accept="image/*" capture="environment" onchange="decodeBarcodePhoto(this)">`);scanner121.start(document.getElementById('scanvideo'));scanmsg.textContent='Scanner actief zodra het beeld verschijnt. Geen herkenning? Gebruik foto of cijfers.'};
window.manualBarcode=(code='',error='')=>{modal('Cijfers onder de barcode',`${error?`<p class="notice">${esc(error)}</p>`:''}${barcodePhotoURL121?`<img src="${esc(barcodePhotoURL121)}" alt="Jouw barcodefoto; lees de cijfers eronder" style="width:100%;max-height:260px;object-fit:contain">`:''}<p class="sub">Neem de cijfers onder de streepjes over en controleer ze. EAN-8, EAN-13, UPC-A, UPC-E en GTIN-14 worden gecontroleerd. Geen automatische cijfer-OCR.</p><label>Barcode<input id="manualcode" inputmode="numeric" autocomplete="off" value="${esc(code)}"></label><button class="btn full" onclick="lookupBarcode(manualcode.value)">Controleer en zoek product</button><button class="btn sec full" onclick="startScan()">Terug naar camera</button>`)};
window.lookupBarcode=async raw=>{let code;try{code=R.barcode(raw)}catch(e){manualBarcode(raw,e.message);return}const local=Object.values(db.products).find(p=>p.barcode===code);if(local){openFood121(local);return}modal('Product zoeken',`<p role="status">Barcode ${esc(code)} opzoeken…</p>`);const token=requestView121,controller=new AbortController();barcodeRequest121=controller;try{const j=await requestJSON121('https://world.openfoodfacts.org/api/v2/product/'+encodeURIComponent(code)+'?fields='+OFF_FIELDS121,controller);if(token!==requestView121)return;if(!j.product){modal('Product niet gevonden',`<p>Deze barcode heeft geen product in Open Food Facts. Neem de waarden over van het etiket.</p>${productForm({barcode:code},code)}`);return}openFood121(R.off({...j.product,code}));}catch(e){if(token!==requestView121)return;modal('Product niet bereikbaar',`<p class="notice">${esc(e.name==='AbortError'?'De bron reageert niet op tijd.':e.message)}</p><button class="btn full" onclick="lookupBarcode('${code}')">Opnieuw proberen</button><button class="btn sec full" onclick="manualBarcode('${code}')">Cijfers controleren</button><button class="btn sec full" onclick="openProductEditor()">Eigen product invoeren</button>`)}};
window.decodeBarcodePhoto=async input=>{const file=input.files?.[0];if(!file)return;scanner121.stop();if(barcodePhotoURL121)URL.revokeObjectURL(barcodePhotoURL121);barcodePhotoURL121=URL.createObjectURL(file);modal('Barcodefoto lezen','<p role="status">Streepjescode analyseren…</p>');const token=requestView121;try{const reader=new ZXingBrowser.BrowserMultiFormatReader(),result=await reader.decodeFromImageUrl(barcodePhotoURL121);if(token===requestView121)manualBarcode(result.getText(),'Barcode herkend. Controleer de cijfers vóór het opzoeken.')}catch(e){if(token===requestView121)manualBarcode('','Streepjescode niet herkend. Lees de cijfers op de foto en voer ze hieronder in.')}};
document.addEventListener('visibilitychange',()=>{if(document.hidden){scanner121.stop();const msg=document.getElementById('scanmsg');if(msg)msg.textContent='Camera gestopt toen de app naar de achtergrond ging. Tik op Camera opnieuw starten.'}});window.addEventListener('pagehide',()=>scanner121.stop());
}
