/* v12 view state never determines the write date of sessions or nutrition. */
let homeDate=today(),lastToday=today(),weekOffset=0;
const argument=x=>esc(JSON.stringify(x));
const fmt=n=>Math.round(n||0).toLocaleString('nl-NL');
const fullDate=d=>new Date(d+'T12:00:00').toLocaleDateString('nl-NL',{weekday:'long',day:'numeric',month:'long',year:'numeric'});
const go=p=>document.querySelector(`[data-p="${p}"]`).click();
function icon(name){const paths={today:'M3 10 12 3l9 7v11h-6v-7H9v7H3Z',workout:'M6 5v14M3 8v8M18 5v14M21 8v8M6 12h12',progress:'M4 3v17h17M7 15l4-5 4 2 5-7',library:'M12 7c-7-5-12 2-8 10 3 6 5 3 8 3s5 3 8-3c4-8-1-15-8-10Zm0 0c0-4 2-5 5-5',settings:'M4 6h16M4 12h16M4 18h16'};return `<svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[name]}"/></svg>`}
function renderHome(){
 const x=BulkyCore.summary(db,homeDate),historical=homeDate!==today(),g=x.goals,t=x.totals;
 const monday=BulkyCore.addDays(today(),-((new Date(today()+'T12:00:00').getDay()+6)%7)+weekOffset*7);
 let message=t.kcal===0?'Ik heb echt energie nodig… Eet iets!':x.score===100?'Alle doelen gehaald. Lekker bezig!':x.sessions.length?'Workout binnen! Tijd om te herstellen.':!x.day.creatine?'Vergeet je creatine niet!':x.plan.name?'Klaar voor '+x.plan.name+'?':'We bouwen rustig verder.';
 const macro=(name,v,target)=>`<div class="macro12"><span>${name}</span><b>${fmt(v)} / ${fmt(target)} g</b><small>${fmt(v/(target||1)*100)}%</small><div class="bar"><div class="fill" style="width:${Math.min(100,v/(target||1)*100)}%"></div></div></div>`;
 const active=Object.values(db.activeSessions).find(w=>w.name===x.plan.name),done=x.sessions.some(w=>w.name===x.plan.name),plan=db.plans[x.plan.name]||[];
 home12.innerHTML=`<header class="homeHead"><div><h1>${historical?'Dagoverzicht':'Vandaag'}</h1><div class="sub">${fullDate(homeDate)}</div></div><button class="theme12" aria-label="Wissel licht en donker" onclick="toggleBulkyTheme();renderHome()">${document.body.classList.contains('bulkyDark')?'☀':'☾'}</button></header>
 <div class="weekHead"><button class="linkbtn touch" aria-label="Vorige week" onclick="changeWeek(-1)">‹</button><button class="linkbtn" onclick="homeDate=today();weekOffset=0;renderHome()">Deze week</button><button class="linkbtn touch" aria-label="Volgende week" onclick="changeWeek(1)">›</button></div><div class="week12" id="week12">${Array.from({length:7},(_,i)=>{const d=BulkyCore.addDays(monday,i),s=BulkyCore.summary(db,d);return `<button class="${d===homeDate?'selected':''}" aria-pressed="${d===homeDate}" onclick="selectHomeDate('${d}')"><small>${['Ma','Di','Wo','Do','Vr','Za','Zo'][i]}</small><b>${+d.slice(-2)}</b><span class="weekDot ${s.sessions.length?'complete':s.plan.name?'planned':''}">${s.sessions.length?'✓':'·'}</span></button>`}).join('')}</div>
 ${historical?'<div class="notice">Daggeschiedenis · alleen bekijken. Nieuwe invoer via Voeding en Workout hoort bij vandaag.</div>':''}
 <div class="mascotCard"><div class="mascotScene state${x.state}"><div class="mascot12" role="img" aria-label="Bulky: ${['uitgeput','weinig energie','op weg','energiek','trots'][x.state/25]}"></div><div class="speech12">${esc(message)}</div></div><button class="score12" style="--score:${x.score}%" onclick="showScore()" aria-label="Dagscore ${x.score} procent, uitleg"><span><b>${x.score}%</b><small>Dagscore</small></span></button></div>
 <div class="card"><div class="between row"><b>Calorieën</b><span class="muted">${fmt(Math.max(0,g.kcal-t.kcal))} over</span></div><div class="kcal12">${fmt(t.kcal)} <span>/ ${fmt(g.kcal)} kcal</span></div><div class="bar"><div class="fill" style="width:${Math.min(100,t.kcal/g.kcal*100)}%"></div></div><div class="macros12">${macro('Eiwit',t.protein,g.protein)}${macro('Koolhydraten',t.carbs,g.carbs||Math.max(1,(g.kcal-g.protein*4-g.kcal*.25)/4))}${macro('Vet',t.fat,g.fat||g.kcal*.25/9)}</div></div>
 <div class="grid2"><button class="card dailyTile" ${historical?'disabled':''} onclick="toggleCreatineV11()"><span>Creatine</span><b>${x.day.creatine?'✓ Genomen':'Nog nemen'}</b><small>${db.profile.creatineGoal||5} g per dag</small></button><button class="card dailyTile" ${historical?'disabled':''} onclick="quickWeightV11()"><span>Gewicht</span><b>${x.day.weight?esc(x.day.weight)+' kg':'＋ Log gewicht'}</b><small>Jouw dagmeting</small></button></div>
 <div class="card"><div class="sub">${historical?'Workout van deze dag':'Workout van vandaag'}</div><h2>${esc(x.plan.name||(x.plan.known?'Rustdag':'Planning onbekend'))}</h2><div class="sub">${x.plan.name?`${plan.length} oefeningen · ${plan.reduce((a,e)=>a+(+e[1]||0),0)} sets`:esc(x.plan.activity||'Herstellen hoort erbij.')}</div>${x.plan.name?`<p class="status12">${done?'✓ Voltooid':active?'Actief':'Gepland · nog niet voltooid'}</p>`:''}${!historical&&x.plan.name&&db.plans[x.plan.name]&&!done?`<button class="btn full" onclick="startWorkout12(${argument(x.plan.name)})">${active?'Ga verder':'Start workout'}</button>`:''}${x.sessions.map(w=>`<div class="item"><b>✓ ${esc(w.name)}</b><div class="sub">${fmt(BulkyCore.volume(w))} kg volume · ${duration12(w)}</div><button class="linkbtn" onclick="showSession12(${argument(w.id)})">Bekijk workout</button></div>`).join('')}</div>
 <div class="sectionHead"><b>${historical?'Gegeten op deze dag':'Vandaag gegeten'}</b>${!historical?'<button class="btn" aria-label="Voeding toevoegen" onclick="openAddMenu()">＋</button>':''}</div><div class="card">${(x.day.foods||[]).map((f,i)=>`<div class="item between row"><div><b>${esc(f.name)}</b><div class="sub">${fmt(f.kcal)} kcal · ${fmt(f.protein)} g eiwit ${f.qtyLabel?'· '+esc(f.qtyLabel):''}</div></div>${!historical?`<button class="linkbtn" onclick="delFood(${i})">Wis</button>`:''}</div>`).join('')||'<p class="muted">Nog niets gelogd.</p>'}</div>`;
 let sx;week12.ontouchstart=e=>sx=e.changedTouches[0].clientX;week12.ontouchend=e=>{const delta=e.changedTouches[0].clientX-sx;if(Math.abs(delta)>60)changeWeek(delta<0?1:-1)};
}
function selectHomeDate(d){homeDate=d;renderHome()}
function changeWeek(n){weekOffset+=n;renderHome()}
function showScore(){modal('Hoe werkt je dagscore?',`<p>Calorieën 45 punten, eiwit 30, geplande gymworkout 15 en creatine 10.</p><p>Op een rustdag vervallen de 15 workoutpunten. De overige 85 punten worden omgerekend naar 100%. Meer eten dan je doel levert geen extra punten op.</p><p>Historische dagen gebruiken de bewaarde doelen. Voor oude v11-dagen zijn de doelen bij migratie bewaard; eerdere doelwijzigingen zijn onbekend.</p>`)}
function duration12(w){return w.startedAt&&w.finishedAt?Math.max(0,Math.round((w.finishedAt-w.startedAt)/60000))+' min':'duur onbekend'}
function startWorkout12(name){selected=name;BulkyCore.start(db,name);save();go('workout');renderWorkout()}
function renderWorkout(){
 const names=[...new Set([...Object.keys(db.plans),...Object.values(db.activeSessions).map(w=>w.name)])];if(!names.includes(selected))selected=names[0];
 wtabs.innerHTML=names.map(n=>`<button class="${n===selected?'on':''}" onclick="selW(${argument(n)})">${esc(n)}</button>`).join('');
 const w=getW(),active=!!w.id;renderedWorkoutDate=w.date;wtitle.textContent=w.name||'Maak een schema';wsub.textContent=fullDate(w.date)+' · '+w.exercises.length+' oefeningen · '+w.exercises.reduce((a,e)=>a+e.sets.length,0)+' sets · '+(active?'Actief':'Nog niet gestart');finish.textContent=active?'Workout afronden':'Start workout';finish.disabled=!w.exercises.length;
 exercises.innerHTML=(!active?'<p class="notice">Start een nieuwe sessie. Vorige prestaties staan ter referentie; je nieuwe sets beginnen leeg.</p>':'')+w.exercises.map((e,ei)=>{const p=prev(e.name),pt=p?p.sets.filter(s=>s.done&&+s.reps).map(s=>`${s.kg||0}×${s.reps}`).join(' · '):'Nog geen voltooide sessie';return `<div class="exercise"><b>${esc(e.name)}</b><div class="sub">${e.sets.length}×${esc(e.range)} reps</div><p class="exercisePrev">Vorige keer: ${esc(pt)}</p><div class="setLabels"><span>Set</span><span>kg</span><span>Reps</span><span>Klaar</span></div>${e.sets.map((s,si)=>`<div class="set"><b>${si+1}</b><input ${active?'':'disabled'} aria-label="Gewicht ${esc(e.name)} set ${si+1}" inputmode="decimal" value="${esc(s.kg)}" placeholder="—" oninput="setv(${ei},${si},'kg',this.value)"><input ${active?'':'disabled'} aria-label="Reps ${esc(e.name)} set ${si+1}" inputmode="numeric" value="${esc(s.reps)}" placeholder="—" oninput="setv(${ei},${si},'reps',this.value)"><button ${active?'':'disabled'} class="btn ${s.done?'good':'sec'}" aria-pressed="${!!s.done}" aria-label="Set ${si+1} voltooid" onclick="setdone(${ei},${si})">${s.done?'✓':'○'}</button></div>`).join('')}</div>`}).join('');
}
window.selW=n=>{selected=n;renderWorkout()};
window.setv=(e,s,k,v)=>{const w=getW();if(!w.id)return;w.exercises[e].sets[s][k]=v.replace(',','.');save()};
window.setdone=(e,s)=>{const w=getW();if(!w.id)return;const set=w.exercises[e].sets[s];if(!set.done&&(!Number.isFinite(+set.kg)||+set.kg<0||!Number.isInteger(+set.reps)||+set.reps<=0))return alert('Vul een geldig gewicht en een positief geheel aantal reps in.');set.done=!set.done;save();if(set.done)startRestTimer(db.workoutSettings.restSeconds||120);renderWorkout()};
finish.onclick=()=>{const w=getW();if(!w.id)return startWorkout12(selected);modal('Workout afronden?',`<p>${esc(w.name)} · ${fullDate(w.date)}</p><p>${w.exercises.flatMap(e=>e.sets).filter(s=>s.done).length} sets afgevinkt · ${fmt(BulkyCore.volume(w))} kg. Alleen afgevinkte sets tellen mee voor volume en records.</p><button class="btn full" onclick="completeWorkout12(${argument(w.id)})">Bevestig en sla definitief op</button>`)};
function completeWorkout12(id){try{const w=BulkyCore.finish(db,id);save();claimWorkoutXP(w);stopRestTimer();closeModal();render();showSession12(w.id)}catch(e){alert(e.message)}}
function showSession12(id){const w=db.workouts[id];if(!w)return;modal(w.name,`<p>✓ Voltooid · ${fullDate(w.date)}</p><p>${fmt(BulkyCore.volume(w))} kg · ${duration12(w)} · ${(w.prs||[]).length} PR’s</p>${w.exercises.map(e=>`<div class="item"><b>${esc(e.name)} · ${e.sets.length}×${esc(e.range||'')}</b><div>${e.sets.map(s=>`${esc(s.kg||0)}×${esc(s.reps||0)} ${s.done?'✓':'(niet afgevinkt)'}`).join(' · ')}</div></div>`).join('')}`)}
window.showWorkoutDay=date=>{const x=BulkyCore.summary(db,date);modal(fullDate(date),`<p>Geplande workout: <b>${esc(x.plan.name||(x.plan.known?'Rustdag':'Onbekend vóór migratie'))}</b></p><p>${x.sessions.length?'✓ '+x.sessions.length+' voltooide sessie(s)':x.plan.name?'Gepland · niet voltooid':'Geen voltooide workout'}</p><p>${fmt(x.totals.kcal)} / ${fmt(x.goals.kcal)} kcal · ${fmt(x.totals.protein)} g eiwit<br>${fmt(x.totals.carbs)} g koolhydraten · ${fmt(x.totals.fat)} g vet<br>Creatine ${x.day.creatine?'✓':'—'} · Gewicht ${esc(x.day.weight||'—')} kg<br>Dagscore ${x.score}%</p>${(x.day.foods||[]).map(f=>`<div class="item">${esc(f.name)} · ${fmt(f.kcal)} kcal</div>`).join('')}${x.sessions.map(w=>`<div class="item"><b>${esc(w.name)}</b><p>${w.exercises.length} oefeningen · ${w.exercises.flatMap(e=>e.sets).filter(s=>s.done).length} sets · ${fmt(BulkyCore.volume(w))} kg · ${duration12(w)}</p><button class="btn sec" onclick="showSession12(${argument(w.id)})">Bekijk workout</button></div>`).join('')}`)};
window.openWorkoutFromDay=window.showWorkoutDay;window.openWorkoutDate=window.showWorkoutDay;
window.editPlans=()=>{modal('Schema & weekplanning',`<p class="sub">Wijzigingen gelden vanaf vandaag. Voltooide en actieve sessies bewaren hun oefeningen.</p>${Object.keys(db.plans).map(n=>`<div class="item between row"><b>${esc(n)}</b><div><button class="linkbtn" onclick="editPlan(${argument(n)})">Wijzig</button> · <button class="linkbtn" onclick="deletePlan(${argument(n)})">Wis</button></div></div>`).join('')}<button class="btn full" onclick="editPlan('')">＋ Workout toevoegen</button><h3>Weekplanning</h3><div id="scheduleRows">${[1,2,3,4,5,6,0].map(d=>{const v=db.scheduleHistory.filter(x=>x.effective<=today()).sort((a,b)=>a.effective.localeCompare(b.effective)).at(-1)||{week:{},activities:{}};return `<div class="item"><label>${D[d]}</label><select data-weekday="${d}"><option value="">Rustdag / andere sport</option>${Object.keys(db.plans).map(n=>`<option value="${esc(n)}" ${n===v.week[d]?'selected':''}>${esc(n)}</option>`).join('')}</select><input data-activity="${d}" aria-label="Andere sport ${D[d]}" placeholder="Andere activiteit (optioneel)" value="${esc(v.activities?.[d]||'')}"></div>`}).join('')}</div><button class="btn full" onclick="saveSchedule12()">Weekplanning opslaan</button>`)};
function saveSchedule12(){const week={},activities={};document.querySelectorAll('[data-weekday]').forEach(el=>week[el.dataset.weekday]=el.value||null);document.querySelectorAll('[data-activity]').forEach(el=>activities[el.dataset.activity]=el.value.trim());BulkyCore.setSchedule(db,week,activities,today());save();closeModal();render()}
window.editPlan=name=>{modal(name?'Workout aanpassen':'Nieuwe workout',`<label>Workoutnaam</label><input id="planName" value="${esc(name)}"><div id="planEx">${(db.plans[name]||[]).map(planExRow).join('')}</div><button class="btn sec full" onclick="addPlanEx()">＋ Oefening</button><button class="btn full" onclick="savePlan(${argument(name)})">Schema opslaan</button>`)};
function planExRow(e=['',3,'8–12']){return `<div class="item"><label>Oefening</label><input class="exn" placeholder="Naam oefening" value="${esc(e[0])}"><div class="qtyrow"><label>Sets<input class="exs" type="number" min="1" max="30" value="${e[1]}"></label><label>Reprange<input class="exr" value="${esc(e[2])}"></label></div><div class="row"><button class="btn sec" aria-label="Oefening omhoog" onclick="moveExercise12(this,-1)">↑</button><button class="btn sec" aria-label="Oefening omlaag" onclick="moveExercise12(this,1)">↓</button><button class="linkbtn" onclick="this.closest('.item').remove()">Verwijder</button></div></div>`}
window.addPlanEx=()=>planEx.insertAdjacentHTML('beforeend',planExRow());
function moveExercise12(b,n){const r=b.closest('.item');if(n<0&&r.previousElementSibling)r.before(r.previousElementSibling);if(n>0&&r.nextElementSibling)r.after(r.nextElementSibling)}
function updateScheduleName(old,name){const v=BulkyCore.copy(db.scheduleHistory.filter(v=>v.effective<=today()).sort((a,b)=>a.effective.localeCompare(b.effective)).at(-1)||{week:{},activities:{}});for(const d in v.week)if(v.week[d]===old)v.week[d]=name;BulkyCore.setSchedule(db,v.week,v.activities||{},today())}
window.savePlan=old=>{const name=planName.value.trim();if(!name)return alert('Vul een naam in.');if(name!==old&&Object.hasOwn(db.plans,name))return alert('Die workoutnaam bestaat al.');const a=[...planEx.children].map(r=>[r.querySelector('.exn').value.trim(),+r.querySelector('.exs').value,r.querySelector('.exr').value.trim()]);if(a.some(e=>!e[0]||!Number.isInteger(e[1])||e[1]<1||e[1]>30||!e[2]))return alert('Controleer oefeningnamen, sets (1–30) en repranges.');if(old&&old!==name){delete db.plans[old];updateScheduleName(old,name)}Object.defineProperty(db.plans,name,{value:a,writable:true,enumerable:true,configurable:true});selected=name;save();closeModal();render()};
window.deletePlan=name=>{if(!confirm('Schema verwijderen? Historische en actieve sessies blijven bewaard.'))return;delete db.plans[name];updateScheduleName(name,null);selected=Object.keys(db.plans)[0];save();render();editPlans()};
window.saveGoals=()=>{const k=+goalK.value,p=+goalP.value,c=+goalCarbs.value,f=+goalFat.value;if(k<=0||p<=0||c<0||f<0)return alert('Controleer je doelen.');db.settings={...db.settings,kcal:k,protein:p,carbs:c||null,fat:f||null};day().goals=clone(db.settings);save();render()};
// Preserve legacy drafts without inventing completion or start times.
function showLegacy12(){modal('Bewaarde oudere workouts',Object.entries(db.legacyWorkouts).map(([id,w])=>`<div class="item"><b>${esc(w.name||id)}</b><p>${esc(w.date||'Datum onbekend')} · ${esc(w.reason||'Historisch record')}</p>${(w.exercises||[]).map(e=>`<div>${esc(e.name)}: ${(e.sets||[]).map(s=>`${esc(s.kg||0)}×${esc(s.reps||0)}`).join(' · ')}</div>`).join('')}</div>`).join('')||'<p>Geen onzekere oudere records.</p>')}
window.exportPlan=()=>downloadJSON12({type:'leanbulk-workout-plan',version:2,plans:db.plans,schedule:db.scheduleHistory.at(-1)},'bulky-schema.json');
function downloadJSON12(data,name){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data)],{type:'application/json'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
window.importPlanFile=async f=>{try{const j=JSON.parse(await f.text());if(j.type!=='leanbulk-workout-plan'||!j.plans||Array.isArray(j.plans)||Object.values(j.plans).some(a=>!Array.isArray(a)||a.some(e=>!Array.isArray(e)||typeof e[0]!=='string'||!Number.isInteger(+e[1])||+e[1]<1||+e[1]>30)))throw Error('Ongeldig schema');if(!confirm('Huidig schema vervangen? Sessies blijven behouden.'))return;db.plans=j.plans;const v=j.schedule||db.scheduleHistory.at(-1),week=clone(v?.week||{});for(const d in week)if(!Object.hasOwn(db.plans,week[d]))week[d]=null;BulkyCore.setSchedule(db,week,v?.activities||{},today());selected=Object.keys(db.plans)[0];save();render()}catch(e){alert(e.message)}};
// Central date rollover refreshes the view, never the actual session date.
function rollover12(){if(today()!==lastToday){if(homeDate===lastToday){homeDate=today();weekOffset=0}lastToday=today();render()}}
setInterval(rollover12,15000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)rollover12()});
window.addEventListener('storage',e=>{if(e.key===KEY&&e.newValue){try{db=normalizeWorkoutData(JSON.parse(e.newValue));renderHome();renderWorkout();renderProgress()}catch{alert('Gegevens zijn gewijzigd in een ander venster. Herlaad de app.')}}});
if(!localStorage.getItem('bulky_theme')&&localStorage.getItem('leanbulk_dark')==='1')localStorage.setItem('bulky_theme','dark');document.body.classList.remove('v11dark');applyBulkyTheme();
document.querySelectorAll('.nav button').forEach(b=>b.innerHTML=icon(b.dataset.p)+`<span>${b.textContent}</span>`);
document.getElementById('bulkyThemeToggle').remove();
const goalsCard=goalK.closest('.card');goalsCard.insertAdjacentHTML('beforeend',`<div class="grid2"><div class="field"><label>Koolhydraten (g, optioneel)</label><input id="goalCarbs" type="number" value="${db.settings.carbs||''}"></div><div class="field"><label>Vet (g, optioneel)</label><input id="goalFat" type="number" value="${db.settings.fat||''}"></div></div><p class="sub">Zonder eigen macrodoelen: 25% van calorieën uit vet; resterende calorieën na eiwit uit koolhydraten.</p>`);
appVersion.insertAdjacentHTML('beforebegin','<div class="card"><button class="btn sec full" onclick="showLegacy12()">Bewaarde oudere workouts bekijken</button></div>');
async function recoveryStore12(mode,value){const store=await new Promise((resolve,reject)=>{const r=indexedDB.open('bulky_recovery_v12',1);r.onupgradeneeded=()=>r.result.createObjectStore('snapshots');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});try{return await new Promise((resolve,reject)=>{const tx=store.transaction('snapshots',mode==='get'?'readonly':'readwrite'),q=mode==='get'?tx.objectStore('snapshots').get('pre_restore'):tx.objectStore('snapshots').put(value,'pre_restore');tx.oncomplete=()=>resolve(q.result);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error)})}finally{store.close()}}
async function replacePhotos12(list){await openIDB();return new Promise((resolve,reject)=>{const tx=idb.transaction('photos','readwrite'),store=tx.objectStore('photos');store.clear();list.forEach(p=>store.put(p));tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error)})}
backupInput.onchange=async()=>{let previous=null,changedPhotos=false;try{const file=backupInput.files?.[0];if(!file)return;const j=JSON.parse(await file.text()),candidate=normalizeWorkoutData(j.data||j);if(j.photos!==undefined&&(!Array.isArray(j.photos)||j.photos.some(p=>!p||!p.id||typeof p.date!=='string'||typeof p.data!=='string')))throw Error('Ongeldige foto’s');if(!confirm('Huidige data vervangen door deze back-up? De huidige data en foto’s worden eerst lokaal als herstelpunt bewaard.'))return;previous={app:'Bulky',version:V,data:clone(db),photos:await allPhotos(),exported:new Date().toISOString()};await recoveryStore12('put',previous);localStorage.setItem(KEY+'_pre_restore',JSON.stringify(db));if(j.photos){await replacePhotos12(j.photos);changedPhotos=true}db=candidate;migrate();location.reload()}catch(e){if(previous){db=previous.data;if(changedPhotos){try{await replacePhotos12(previous.photos)}catch{alert('Automatisch fotoherstel mislukt. Download het herstelpunt in Instellingen.')}}try{save()}catch{}}alert('Import niet voltooid: '+e.message)}finally{backupInput.value=''}};
async function downloadRecovery12(){try{const snapshot=await recoveryStore12('get');if(!snapshot)return alert('Er is nog geen importherstelpunt.');downloadJSON12(snapshot,'bulky-herstelpunt.json')}catch(e){alert('Herstelpunt niet beschikbaar: '+e.message)}}
appVersion.insertAdjacentHTML('beforebegin','<div class="card"><button class="btn sec full" onclick="downloadRecovery12()">Herstelpunt vóór laatste import downloaden</button></div>');
const finishOnboardingOriginal=window.finishOnboarding;window.finishOnboarding=()=>{finishOnboardingOriginal();day().goals=clone(db.settings);if(onPlan.value==='empty')BulkyCore.setSchedule(db,{},{},today());save();render()};
window.saveQuickWeightV11=()=>{const value=decimal(qw11.value);if(!Number.isFinite(value)||value<=0)return alert('Vul een geldig gewicht in.');day().weight=value;save();closeModal();render()};
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
render();if(!hadExistingData)setTimeout(showOnboarding,120);
